packages:
  - packages/*

catalog:
  "@tanstack/react-query": ^5.90.21
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@types/vscode-webview": ^1.57.5
  "@vitejs/plugin-react": ^5.1.4
  "@vscode-elements/react-elements": ^2.4.0
  "@vscode/codicons": ^0.0.44
  babel-plugin-react-compiler: ^1.0.0
  coder: github:coder/coder#main
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ^5.9.3
  vite: ^7.3.1

catalogMode: strict

onlyBuiltDependencies:
  - "@vscode/vsce-sign"
  - bufferutil
  - electron
  - esbuild
  - keytar
  - unrs-resolver
  - utf-8-validate
