packages:
  - packages/*

catalog:
  "@rolldown/plugin-babel": ^0.2.3
  "@storybook/addon-a11y": ^10.4.6
  "@storybook/addon-docs": ^10.4.6
  "@storybook/react-vite": ^10.4.6
  "@tanstack/react-query": ^5.101.2
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  "@types/vscode-webview": ^1.57.5
  "@vitejs/plugin-react": ^6.0.3
  "@vscode-elements/react-elements": ^2.4.0
  "@vscode/codicons": ^0.0.45
  babel-plugin-react-compiler: ^1.0.0
  coder: github:coder/coder#v2.34.1
  date-fns: ^4.4.0
  react: ^19.2.7
  react-dom: ^19.2.7
  typescript: ^6.0.3
  vite: ^8.1.0

catalogMode: strict

dedupePeers: true

allowBuilds:
  "@vscode/vsce-sign": true
  bufferutil: true
  electron: true
  esbuild: true
  keytar: false
  unrs-resolver: true
  utf-8-validate: true

overrides:
  "@vscode-elements/elements": ^2.5.1
