/** @type {[string, string][]} */
export const theme = [
  ["--vscode-actionBar-toggledBackground", "rgba(42, 161, 152, 0.24)"],
  ["--vscode-activityBar-activeBorder", "#ffffff"],
  ["--vscode-activityBar-background", "#003847"],
  ["--vscode-activityBar-dropBorder", "#ffffff"],
  ["--vscode-activityBar-foreground", "#ffffff"],
  ["--vscode-activityBar-inactiveForeground", "rgba(255, 255, 255, 0.4)"],
  ["--vscode-activityBarBadge-background", "#007acc"],
  ["--vscode-activityBarBadge-foreground", "#ffffff"],
  ["--vscode-activityBarTop-activeBorder", "#e7e7e7"],
  ["--vscode-activityBarTop-dropBorder", "#e7e7e7"],
  ["--vscode-activityBarTop-foreground", "#e7e7e7"],
  ["--vscode-activityBarTop-inactiveForeground", "rgba(231, 231, 231, 0.6)"],
  ["--vscode-activityErrorBadge-background", "#f14c4c"],
  ["--vscode-activityErrorBadge-foreground", "#000000"],
  ["--vscode-activityWarningBadge-background", "#b27c00"],
  ["--vscode-activityWarningBadge-foreground", "#ffffff"],
  ["--vscode-agentSessionReadIndicator-foreground", "rgba(204, 204, 204, 0.2)"],
  ["--vscode-agentSessionSelectedBadge-border", "rgba(255, 255, 255, 0.3)"],
  ["--vscode-agentSessionSelectedUnfocusedBadge-border", "rgba(204, 204, 204, 0.3)"],
  ["--vscode-agentStatusIndicator-background", "rgba(255, 255, 255, 0.05)"],
  ["--vscode-aiCustomizationManagement-sashBorder", "#2b2b4a"],
  ["--vscode-badge-background", "#047aa6"],
  ["--vscode-badge-foreground", "#ffffff"],
  ["--vscode-banner-background", "#005a6f"],
  ["--vscode-banner-foreground", "#ffffff"],
  ["--vscode-banner-iconForeground", "#59a4f9"],
  ["--vscode-bodyFontSize", "13px"],
  ["--vscode-bodyFontSize-small", "12px"],
  ["--vscode-bodyFontSize-xSmall", "11px"],
  ["--vscode-breadcrumb-activeSelectionForeground", "#e0e0e0"],
  ["--vscode-breadcrumb-background", "#002b36"],
  ["--vscode-breadcrumb-focusForeground", "#e0e0e0"],
  ["--vscode-breadcrumb-foreground", "rgba(204, 204, 204, 0.8)"],
  ["--vscode-breadcrumbPicker-background", "#00212b"],
  ["--vscode-browser-border", "#003847"],
  ["--vscode-button-background", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-button-foreground", "#ffffff"],
  ["--vscode-button-hoverBackground", "rgba(50, 193, 181, 0.6)"],
  ["--vscode-button-secondaryBackground", "rgba(0, 68, 84, 0.67)"],
  ["--vscode-button-secondaryForeground", "#cccccc"],
  ["--vscode-button-secondaryHoverBackground", "rgba(0, 82, 101, 0.67)"],
  ["--vscode-button-separator", "rgba(255, 255, 255, 0.4)"],
  ["--vscode-chart-axis", "rgba(191, 191, 191, 0.4)"],
  ["--vscode-chart-guide", "rgba(191, 191, 191, 0.2)"],
  ["--vscode-chart-line", "#236b8e"],
  ["--vscode-charts-blue", "#59a4f9"],
  ["--vscode-charts-foreground", "#cccccc"],
  ["--vscode-charts-green", "#89d185"],
  ["--vscode-charts-lines", "rgba(204, 204, 204, 0.5)"],
  ["--vscode-charts-orange", "rgba(234, 92, 0, 0.33)"],
  ["--vscode-charts-purple", "#b180d7"],
  ["--vscode-charts-red", "#f14c4c"],
  ["--vscode-charts-yellow", "#cca700"],
  ["--vscode-chat-avatarBackground", "#1f1f1f"],
  ["--vscode-chat-avatarForeground", "#cccccc"],
  ["--vscode-chat-checkpointSeparator", "#585858"],
  ["--vscode-chat-editedFileForeground", "#e2c08d"],
  ["--vscode-chat-linesAddedForeground", "#54b054"],
  ["--vscode-chat-linesRemovedForeground", "#fc6a6a"],
  ["--vscode-chat-requestBackground", "rgba(0, 43, 54, 0.62)"],
  ["--vscode-chat-requestBorder", "rgba(255, 255, 255, 0.1)"],
  ["--vscode-chat-requestBubbleBackground", "rgba(39, 70, 66, 0.3)"],
  ["--vscode-chat-requestBubbleHoverBackground", "rgba(39, 70, 66, 0.6)"],
  ["--vscode-chat-requestCodeBorder", "rgba(0, 73, 114, 0.72)"],
  ["--vscode-chat-slashCommandBackground", "rgba(38, 71, 120, 0.4)"],
  ["--vscode-chat-slashCommandForeground", "#85b6ff"],
  ["--vscode-chat-thinkingShimmer", "#ffffff"],
  ["--vscode-chatManagement-sashBorder", "#2b2b4a"],
  ["--vscode-checkbox-background", "#00212b"],
  ["--vscode-checkbox-border", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-checkbox-disabled\.background", "#4f656c"],
  ["--vscode-checkbox-disabled\.foreground", "#a0abae"],
  ["--vscode-checkbox-foreground", "#f0f0f0"],
  ["--vscode-checkbox-selectBackground", "#00212b"],
  ["--vscode-checkbox-selectBorder", "#c5c5c5"],
  ["--vscode-codiconFontSize", "16px"],
  ["--vscode-commandCenter-activeBackground", "rgba(255, 255, 255, 0.08)"],
  ["--vscode-commandCenter-activeBorder", "rgba(204, 204, 204, 0.3)"],
  ["--vscode-commandCenter-activeForeground", "#cccccc"],
  ["--vscode-commandCenter-background", "rgba(255, 255, 255, 0.05)"],
  ["--vscode-commandCenter-border", "rgba(204, 204, 204, 0.2)"],
  ["--vscode-commandCenter-debuggingBackground", "rgba(0, 33, 43, 0.26)"],
  ["--vscode-commandCenter-foreground", "#cccccc"],
  ["--vscode-commandCenter-inactiveBorder", "rgba(204, 204, 204, 0.15)"],
  ["--vscode-commandCenter-inactiveForeground", "rgba(204, 204, 204, 0.6)"],
  ["--vscode-commentsView-resolvedIcon", "rgba(204, 204, 204, 0.5)"],
  ["--vscode-commentsView-unresolvedIcon", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-cornerRadius-circle", "9999px"],
  ["--vscode-cornerRadius-large", "8px"],
  ["--vscode-cornerRadius-medium", "6px"],
  ["--vscode-cornerRadius-small", "4px"],
  ["--vscode-cornerRadius-xLarge", "12px"],
  ["--vscode-cornerRadius-xSmall", "2px"],
  ["--vscode-debugConsole-errorForeground", "#ffeaea"],
  ["--vscode-debugConsole-infoForeground", "#59a4f9"],
  ["--vscode-debugConsole-sourceForeground", "#cccccc"],
  ["--vscode-debugConsole-warningForeground", "#cca700"],
  ["--vscode-debugConsoleInputIcon-foreground", "#cccccc"],
  ["--vscode-debugExceptionWidget-background", "#00212b"],
  ["--vscode-debugExceptionWidget-border", "#ab395b"],
  ["--vscode-debugIcon-breakpointCurrentStackframeForeground", "#ffcc00"],
  ["--vscode-debugIcon-breakpointDisabledForeground", "#848484"],
  ["--vscode-debugIcon-breakpointForeground", "#e51400"],
  ["--vscode-debugIcon-breakpointStackframeForeground", "#89d185"],
  ["--vscode-debugIcon-breakpointUnverifiedForeground", "#848484"],
  ["--vscode-debugIcon-continueForeground", "#75beff"],
  ["--vscode-debugIcon-disconnectForeground", "#f48771"],
  ["--vscode-debugIcon-pauseForeground", "#75beff"],
  ["--vscode-debugIcon-restartForeground", "#89d185"],
  ["--vscode-debugIcon-startForeground", "#89d185"],
  ["--vscode-debugIcon-stepBackForeground", "#75beff"],
  ["--vscode-debugIcon-stepIntoForeground", "#75beff"],
  ["--vscode-debugIcon-stepOutForeground", "#75beff"],
  ["--vscode-debugIcon-stepOverForeground", "#75beff"],
  ["--vscode-debugIcon-stopForeground", "#f48771"],
  ["--vscode-debugTokenExpression-boolean", "#4e94ce"],
  ["--vscode-debugTokenExpression-error", "#f48771"],
  ["--vscode-debugTokenExpression-name", "#c586c0"],
  ["--vscode-debugTokenExpression-number", "#b5cea8"],
  ["--vscode-debugTokenExpression-string", "#ce9178"],
  ["--vscode-debugTokenExpression-type", "#4a90e2"],
  ["--vscode-debugTokenExpression-value", "rgba(204, 204, 204, 0.6)"],
  ["--vscode-debugToolBar-background", "#00212b"],
  ["--vscode-debugView-exceptionLabelBackground", "#6c2022"],
  ["--vscode-debugView-exceptionLabelForeground", "#cccccc"],
  ["--vscode-debugView-stateLabelBackground", "rgba(136, 136, 136, 0.27)"],
  ["--vscode-debugView-stateLabelForeground", "#cccccc"],
  ["--vscode-debugView-valueChangedHighlight", "#569cd6"],
  ["--vscode-descriptionForeground", "rgba(204, 204, 204, 0.7)"],
  ["--vscode-diffEditor-diagonalFill", "rgba(204, 204, 204, 0.2)"],
  ["--vscode-diffEditor-insertedLineBackground", "rgba(155, 185, 85, 0.2)"],
  ["--vscode-diffEditor-insertedTextBackground", "rgba(156, 204, 44, 0.2)"],
  ["--vscode-diffEditor-move\.border", "rgba(139, 139, 139, 0.61)"],
  ["--vscode-diffEditor-moveActive\.border", "#ffa500"],
  ["--vscode-diffEditor-removedLineBackground", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-diffEditor-removedTextBackground", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-diffEditor-unchangedCodeBackground", "rgba(116, 116, 116, 0.16)"],
  ["--vscode-diffEditor-unchangedRegionBackground", "#00212b"],
  ["--vscode-diffEditor-unchangedRegionForeground", "#cccccc"],
  ["--vscode-diffEditor-unchangedRegionShadow", "#000000"],
  ["--vscode-disabledForeground", "rgba(204, 204, 204, 0.5)"],
  ["--vscode-dropdown-background", "#00212b"],
  ["--vscode-dropdown-border", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-dropdown-foreground", "#f0f0f0"],
  ["--vscode-editor-background", "#002b36"],
  ["--vscode-editor-compositionBorder", "#ffffff"],
  ["--vscode-editor-findMatchBackground", "#515c6a"],
  ["--vscode-editor-findMatchHighlightBackground", "rgba(234, 92, 0, 0.33)"],
  ["--vscode-editor-findRangeHighlightBackground", "rgba(58, 61, 65, 0.4)"],
  ["--vscode-editor-focusedStackFrameHighlightBackground", "rgba(122, 189, 122, 0.3)"],
  ["--vscode-editor-foldBackground", "rgba(39, 70, 66, 0.3)"],
  ["--vscode-editor-foldPlaceholderForeground", "#808080"],
  ["--vscode-editor-font-feature-settings", "\"liga\" off, \"calt\" off"],
  ["--vscode-editor-font-size", "14px"],
  ["--vscode-editor-font-weight", "normal"],
  ["--vscode-editor-foreground", "#839496"],
  ["--vscode-editor-hoverHighlightBackground", "rgba(38, 79, 120, 0.25)"],
  ["--vscode-editor-inactiveLineHighlightBackground", "#073642"],
  ["--vscode-editor-inactiveSelectionBackground", "rgba(39, 70, 66, 0.5)"],
  ["--vscode-editor-inlineValuesBackground", "rgba(255, 200, 0, 0.2)"],
  ["--vscode-editor-inlineValuesForeground", "rgba(255, 255, 255, 0.5)"],
  ["--vscode-editor-lineHighlightBackground", "#073642"],
  ["--vscode-editor-lineHighlightBorder", "#282828"],
  ["--vscode-editor-linkedEditingBackground", "rgba(255, 0, 0, 0.3)"],
  ["--vscode-editor-placeholder\.foreground", "rgba(255, 255, 255, 0.34)"],
  ["--vscode-editor-rangeHighlightBackground", "rgba(255, 255, 255, 0.04)"],
  ["--vscode-editor-selectionBackground", "#274642"],
  ["--vscode-editor-selectionHighlightBackground", "rgba(0, 90, 111, 0.67)"],
  ["--vscode-editor-snippetFinalTabstopHighlightBorder", "#525252"],
  ["--vscode-editor-snippetTabstopHighlightBackground", "rgba(124, 124, 124, 0.3)"],
  ["--vscode-editor-stackFrameHighlightBackground", "rgba(255, 255, 0, 0.2)"],
  ["--vscode-editor-symbolHighlightBackground", "rgba(234, 92, 0, 0.33)"],
  ["--vscode-editor-wordHighlightBackground", "rgba(0, 68, 84, 0.67)"],
  ["--vscode-editor-wordHighlightStrongBackground", "rgba(0, 90, 111, 0.67)"],
  ["--vscode-editor-wordHighlightTextBackground", "rgba(0, 68, 84, 0.67)"],
  ["--vscode-editorActionList-background", "#00212b"],
  ["--vscode-editorActionList-focusBackground", "#005a6f"],
  ["--vscode-editorActionList-focusForeground", "#ffffff"],
  ["--vscode-editorActionList-foreground", "#cccccc"],
  ["--vscode-editorActiveLineNumber-foreground", "#c6c6c6"],
  ["--vscode-editorBracketHighlight-foreground1", "#cdcdcd"],
  ["--vscode-editorBracketHighlight-foreground2", "#b58900"],
  ["--vscode-editorBracketHighlight-foreground3", "#d33682"],
  ["--vscode-editorBracketHighlight-foreground4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketHighlight-foreground5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketHighlight-foreground6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketHighlight-unexpectedBracket\.foreground", "rgba(255, 18, 18, 0.8)"],
  ["--vscode-editorBracketMatch-background", "rgba(0, 100, 0, 0.1)"],
  ["--vscode-editorBracketMatch-border", "#888888"],
  ["--vscode-editorBracketPairGuide-activeBackground1", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground2", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground3", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background1", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background2", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background3", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorCodeLens-foreground", "#999999"],
  ["--vscode-editorCommentsWidget-rangeActiveBackground", "rgba(42, 161, 152, 0.06)"],
  ["--vscode-editorCommentsWidget-rangeBackground", "rgba(42, 161, 152, 0.06)"],
  ["--vscode-editorCommentsWidget-replyInputBackground", "#00212b"],
  ["--vscode-editorCommentsWidget-resolvedBorder", "rgba(204, 204, 204, 0.5)"],
  ["--vscode-editorCommentsWidget-unresolvedBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-editorCursor-foreground", "#d30102"],
  ["--vscode-editorError-foreground", "#f14c4c"],
  ["--vscode-editorGhostText-foreground", "rgba(255, 255, 255, 0.34)"],
  ["--vscode-editorGroup-border", "#00212b"],
  ["--vscode-editorGroup-dropBackground", "rgba(42, 161, 152, 0.27)"],
  ["--vscode-editorGroup-dropIntoPromptBackground", "#00212b"],
  ["--vscode-editorGroup-dropIntoPromptForeground", "#cccccc"],
  ["--vscode-editorGroupHeader-noTabsBackground", "#002b36"],
  ["--vscode-editorGroupHeader-tabsBackground", "#004052"],
  ["--vscode-editorGutter-addedBackground", "#487e02"],
  ["--vscode-editorGutter-addedSecondaryBackground", "#243f01"],
  ["--vscode-editorGutter-background", "#002b36"],
  ["--vscode-editorGutter-commentDraftGlyphForeground", "#839496"],
  ["--vscode-editorGutter-commentGlyphForeground", "#839496"],
  ["--vscode-editorGutter-commentRangeForeground", "#003845"],
  ["--vscode-editorGutter-commentUnresolvedGlyphForeground", "#839496"],
  ["--vscode-editorGutter-deletedBackground", "#f14c4c"],
  ["--vscode-editorGutter-deletedSecondaryBackground", "#b00e0e"],
  ["--vscode-editorGutter-foldingControlForeground", "#c5c5c5"],
  ["--vscode-editorGutter-itemBackground", "#003845"],
  ["--vscode-editorGutter-itemGlyphForeground", "#839496"],
  ["--vscode-editorGutter-modifiedBackground", "#1b81a8"],
  ["--vscode-editorGutter-modifiedSecondaryBackground", "#0d4054"],
  ["--vscode-editorHint-foreground", "rgba(238, 238, 238, 0.7)"],
  ["--vscode-editorHoverWidget-background", "#004052"],
  ["--vscode-editorHoverWidget-border", "#454545"],
  ["--vscode-editorHoverWidget-foreground", "#cccccc"],
  ["--vscode-editorHoverWidget-highlightForeground", "#1ebcc5"],
  ["--vscode-editorHoverWidget-statusBarBackground", "#004d62"],
  ["--vscode-editorIndentGuide-activeBackground", "rgba(195, 225, 225, 0.5)"],
  ["--vscode-editorIndentGuide-activeBackground1", "rgba(195, 225, 225, 0.5)"],
  ["--vscode-editorIndentGuide-activeBackground2", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-activeBackground3", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-activeBackground4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-activeBackground5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-activeBackground6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background", "rgba(147, 161, 161, 0.5)"],
  ["--vscode-editorIndentGuide-background1", "rgba(147, 161, 161, 0.5)"],
  ["--vscode-editorIndentGuide-background2", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background3", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorInfo-foreground", "#59a4f9"],
  ["--vscode-editorInlayHint-background", "rgba(4, 122, 166, 0.1)"],
  ["--vscode-editorInlayHint-foreground", "#969696"],
  ["--vscode-editorInlayHint-parameterBackground", "rgba(4, 122, 166, 0.1)"],
  ["--vscode-editorInlayHint-parameterForeground", "#969696"],
  ["--vscode-editorInlayHint-typeBackground", "rgba(4, 122, 166, 0.1)"],
  ["--vscode-editorInlayHint-typeForeground", "#969696"],
  ["--vscode-editorLightBulb-foreground", "#ffcc00"],
  ["--vscode-editorLightBulbAi-foreground", "#ffcc00"],
  ["--vscode-editorLightBulbAutoFix-foreground", "#75beff"],
  ["--vscode-editorLineNumber-activeForeground", "#949494"],
  ["--vscode-editorLineNumber-foreground", "#858585"],
  ["--vscode-editorLink-activeForeground", "#4e94ce"],
  ["--vscode-editorMarkerNavigation-background", "#002b36"],
  ["--vscode-editorMarkerNavigationError-background", "#ab395b"],
  ["--vscode-editorMarkerNavigationError-headerBackground", "rgba(171, 57, 91, 0.1)"],
  ["--vscode-editorMarkerNavigationInfo-background", "#59a4f9"],
  ["--vscode-editorMarkerNavigationInfo-headerBackground", "rgba(89, 164, 249, 0.1)"],
  ["--vscode-editorMarkerNavigationWarning-background", "#5b7e7a"],
  ["--vscode-editorMarkerNavigationWarning-headerBackground", "rgba(91, 126, 122, 0.1)"],
  ["--vscode-editorMinimap-inlineChatInserted", "rgba(156, 204, 44, 0.12)"],
  ["--vscode-editorMultiCursor-primary\.foreground", "#d30102"],
  ["--vscode-editorMultiCursor-secondary\.foreground", "#d30102"],
  ["--vscode-editorOverviewRuler-addedForeground", "rgba(72, 126, 2, 0.6)"],
  ["--vscode-editorOverviewRuler-border", "rgba(127, 127, 127, 0.3)"],
  ["--vscode-editorOverviewRuler-bracketMatchForeground", "#a0a0a0"],
  ["--vscode-editorOverviewRuler-commentDraftForeground", "#003845"],
  ["--vscode-editorOverviewRuler-commentForeground", "#003845"],
  ["--vscode-editorOverviewRuler-commentUnresolvedForeground", "#003845"],
  ["--vscode-editorOverviewRuler-commonContentForeground", "rgba(96, 96, 96, 0.4)"],
  ["--vscode-editorOverviewRuler-currentContentForeground", "rgba(64, 200, 174, 0.5)"],
  ["--vscode-editorOverviewRuler-deletedForeground", "rgba(241, 76, 76, 0.6)"],
  ["--vscode-editorOverviewRuler-errorForeground", "rgba(255, 18, 18, 0.7)"],
  ["--vscode-editorOverviewRuler-findMatchForeground", "rgba(209, 134, 22, 0.49)"],
  ["--vscode-editorOverviewRuler-incomingContentForeground", "rgba(64, 166, 255, 0.5)"],
  ["--vscode-editorOverviewRuler-infoForeground", "#59a4f9"],
  ["--vscode-editorOverviewRuler-inlineChatInserted", "rgba(156, 204, 44, 0.12)"],
  ["--vscode-editorOverviewRuler-inlineChatRemoved", "rgba(255, 0, 0, 0.12)"],
  ["--vscode-editorOverviewRuler-modifiedForeground", "rgba(27, 129, 168, 0.6)"],
  ["--vscode-editorOverviewRuler-rangeHighlightForeground", "rgba(0, 122, 204, 0.6)"],
  ["--vscode-editorOverviewRuler-selectionHighlightForeground", "rgba(160, 160, 160, 0.8)"],
  ["--vscode-editorOverviewRuler-warningForeground", "#cca700"],
  ["--vscode-editorOverviewRuler-wordHighlightForeground", "rgba(160, 160, 160, 0.8)"],
  ["--vscode-editorOverviewRuler-wordHighlightStrongForeground", "rgba(192, 160, 192, 0.8)"],
  ["--vscode-editorOverviewRuler-wordHighlightTextForeground", "rgba(160, 160, 160, 0.8)"],
  ["--vscode-editorPane-background", "#002b36"],
  ["--vscode-editorRuler-foreground", "#5a5a5a"],
  ["--vscode-editorStickyScroll-background", "#002b36"],
  ["--vscode-editorStickyScroll-shadow", "#000000"],
  ["--vscode-editorStickyScrollGutter-background", "#002b36"],
  ["--vscode-editorStickyScrollHover-background", "#2a2d2e"],
  ["--vscode-editorSuggestWidget-background", "#00212b"],
  ["--vscode-editorSuggestWidget-border", "#454545"],
  ["--vscode-editorSuggestWidget-focusHighlightForeground", "#1ebcc5"],
  ["--vscode-editorSuggestWidget-foreground", "#839496"],
  ["--vscode-editorSuggestWidget-highlightForeground", "#1ebcc5"],
  ["--vscode-editorSuggestWidget-selectedBackground", "#005a6f"],
  ["--vscode-editorSuggestWidget-selectedForeground", "#ffffff"],
  ["--vscode-editorSuggestWidgetStatus-foreground", "rgba(131, 148, 150, 0.5)"],
  ["--vscode-editorUnicodeHighlight-border", "#cca700"],
  ["--vscode-editorUnnecessaryCode-opacity", "rgba(0, 0, 0, 0.67)"],
  ["--vscode-editorWarning-foreground", "#cca700"],
  ["--vscode-editorWhitespace-foreground", "rgba(147, 161, 161, 0.5)"],
  ["--vscode-editorWidget-background", "#00212b"],
  ["--vscode-editorWidget-border", "#454545"],
  ["--vscode-editorWidget-foreground", "#cccccc"],
  ["--vscode-errorForeground", "#ffeaea"],
  ["--vscode-extensionBadge-remoteBackground", "#007acc"],
  ["--vscode-extensionBadge-remoteForeground", "#ffffff"],
  ["--vscode-extensionButton-background", "rgba(0, 68, 84, 0.67)"],
  ["--vscode-extensionButton-foreground", "#cccccc"],
  ["--vscode-extensionButton-hoverBackground", "rgba(0, 82, 101, 0.67)"],
  ["--vscode-extensionButton-prominentBackground", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-extensionButton-prominentForeground", "#ffffff"],
  ["--vscode-extensionButton-prominentHoverBackground", "rgba(50, 193, 181, 0.6)"],
  ["--vscode-extensionButton-separator", "rgba(255, 255, 255, 0.4)"],
  ["--vscode-extensionIcon-preReleaseForeground", "#1d9271"],
  ["--vscode-extensionIcon-privateForeground", "rgba(255, 255, 255, 0.38)"],
  ["--vscode-extensionIcon-sponsorForeground", "#d758b3"],
  ["--vscode-extensionIcon-starForeground", "#ff8e00"],
  ["--vscode-extensionIcon-verifiedForeground", "#3794ff"],
  ["--vscode-focusBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-font-size", "13px"],
  ["--vscode-font-weight", "normal"],
  ["--vscode-foreground", "#cccccc"],
  ["--vscode-gauge-background", "rgba(54, 59, 95, 0.3)"],
  ["--vscode-gauge-errorBackground", "rgba(169, 32, 73, 0.3)"],
  ["--vscode-gauge-errorForeground", "#a92049"],
  ["--vscode-gauge-foreground", "#363b5f"],
  ["--vscode-gauge-warningBackground", "rgba(157, 138, 94, 0.3)"],
  ["--vscode-gauge-warningForeground", "#9d8a5e"],
  ["--vscode-icon-foreground", "#c5c5c5"],
  ["--vscode-inlineChat-background", "#00212b"],
  ["--vscode-inlineChat-border", "#454545"],
  ["--vscode-inlineChat-foreground", "#cccccc"],
  ["--vscode-inlineChat-shadow", "rgba(0, 0, 0, 0.36)"],
  ["--vscode-inlineChatDiff-inserted", "rgba(156, 204, 44, 0.1)"],
  ["--vscode-inlineChatDiff-removed", "rgba(255, 0, 0, 0.1)"],
  ["--vscode-inlineChatInput-background", "#003847"],
  ["--vscode-inlineChatInput-border", "#454545"],
  ["--vscode-inlineChatInput-focusBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-inlineChatInput-placeholderForeground", "rgba(147, 161, 161, 0.67)"],
  ["--vscode-inlineEdit-gutterIndicator\.background", "rgba(0, 64, 82, 0.5)"],
  ["--vscode-inlineEdit-gutterIndicator\.primaryBackground", "rgba(42, 161, 152, 0.24)"],
  ["--vscode-inlineEdit-gutterIndicator\.primaryBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-inlineEdit-gutterIndicator\.primaryForeground", "#ffffff"],
  ["--vscode-inlineEdit-gutterIndicator\.secondaryBackground", "#004052"],
  ["--vscode-inlineEdit-gutterIndicator\.secondaryBorder", "#454545"],
  ["--vscode-inlineEdit-gutterIndicator\.secondaryForeground", "#cccccc"],
  ["--vscode-inlineEdit-gutterIndicator\.successfulBackground", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-inlineEdit-gutterIndicator\.successfulBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-inlineEdit-gutterIndicator\.successfulForeground", "#ffffff"],
  ["--vscode-inlineEdit-modifiedBackground", "rgba(156, 204, 44, 0.06)"],
  ["--vscode-inlineEdit-modifiedBorder", "rgba(156, 204, 44, 0.2)"],
  ["--vscode-inlineEdit-modifiedChangedLineBackground", "rgba(155, 185, 85, 0.14)"],
  ["--vscode-inlineEdit-modifiedChangedTextBackground", "rgba(156, 204, 44, 0.14)"],
  ["--vscode-inlineEdit-originalBackground", "rgba(255, 0, 0, 0.04)"],
  ["--vscode-inlineEdit-originalBorder", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-inlineEdit-originalChangedLineBackground", "rgba(255, 0, 0, 0.16)"],
  ["--vscode-inlineEdit-originalChangedTextBackground", "rgba(255, 0, 0, 0.16)"],
  ["--vscode-inlineEdit-tabWillAcceptModifiedBorder", "rgba(156, 204, 44, 0.2)"],
  ["--vscode-inlineEdit-tabWillAcceptOriginalBorder", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-input-background", "#003847"],
  ["--vscode-input-foreground", "#93a1a1"],
  ["--vscode-input-placeholderForeground", "rgba(147, 161, 161, 0.67)"],
  ["--vscode-inputOption-activeBackground", "rgba(42, 161, 152, 0.24)"],
  ["--vscode-inputOption-activeBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-inputOption-activeForeground", "#ffffff"],
  ["--vscode-inputOption-hoverBackground", "rgba(90, 93, 94, 0.5)"],
  ["--vscode-inputValidation-errorBackground", "#571b26"],
  ["--vscode-inputValidation-errorBorder", "#a92049"],
  ["--vscode-inputValidation-infoBackground", "#052730"],
  ["--vscode-inputValidation-infoBorder", "#363b5f"],
  ["--vscode-inputValidation-warningBackground", "#5d5938"],
  ["--vscode-inputValidation-warningBorder", "#9d8a5e"],
  ["--vscode-interactive-activeCodeBorder", "#2b2b4a"],
  ["--vscode-interactive-inactiveCodeBorder", "rgba(0, 68, 84, 0.53)"],
  ["--vscode-keybindingLabel-background", "rgba(128, 128, 128, 0.17)"],
  ["--vscode-keybindingLabel-border", "rgba(51, 51, 51, 0.6)"],
  ["--vscode-keybindingLabel-bottomBorder", "rgba(68, 68, 68, 0.6)"],
  ["--vscode-keybindingLabel-foreground", "#cccccc"],
  ["--vscode-keybindingTable-headerBackground", "rgba(204, 204, 204, 0.04)"],
  ["--vscode-keybindingTable-rowsBackground", "rgba(204, 204, 204, 0.04)"],
  ["--vscode-list-activeSelectionBackground", "#005a6f"],
  ["--vscode-list-activeSelectionForeground", "#ffffff"],
  ["--vscode-list-deemphasizedForeground", "#8c8c8c"],
  ["--vscode-list-dropBackground", "rgba(0, 68, 84, 0.53)"],
  ["--vscode-list-dropBetweenBackground", "#c5c5c5"],
  ["--vscode-list-errorForeground", "#f88070"],
  ["--vscode-list-filterMatchBackground", "rgba(234, 92, 0, 0.33)"],
  ["--vscode-list-focusHighlightForeground", "#1ebcc5"],
  ["--vscode-list-focusOutline", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-list-highlightForeground", "#1ebcc5"],
  ["--vscode-list-hoverBackground", "rgba(0, 68, 84, 0.67)"],
  ["--vscode-list-inactiveSelectionBackground", "rgba(0, 68, 84, 0.53)"],
  ["--vscode-list-invalidItemForeground", "#b89500"],
  ["--vscode-list-warningForeground", "#cca700"],
  ["--vscode-listFilterWidget-background", "#00212b"],
  ["--vscode-listFilterWidget-noMatchesOutline", "#be1100"],
  ["--vscode-listFilterWidget-outline", "rgba(0, 0, 0, 0)"],
  ["--vscode-listFilterWidget-shadow", "rgba(0, 0, 0, 0.36)"],
  ["--vscode-markdownAlert-caution\.foreground", "#f14c4c"],
  ["--vscode-markdownAlert-important\.foreground", "#b180d7"],
  ["--vscode-markdownAlert-note\.foreground", "#59a4f9"],
  ["--vscode-markdownAlert-tip\.foreground", "#89d185"],
  ["--vscode-markdownAlert-warning\.foreground", "#cca700"],
  ["--vscode-mcpIcon-starForeground", "#ff8e00"],
  ["--vscode-menu-background", "#00212b"],
  ["--vscode-menu-foreground", "#f0f0f0"],
  ["--vscode-menu-selectionBackground", "#005a6f"],
  ["--vscode-menu-selectionForeground", "#ffffff"],
  ["--vscode-menu-separatorBackground", "#606060"],
  ["--vscode-menubar-selectionBackground", "rgba(90, 93, 94, 0.31)"],
  ["--vscode-menubar-selectionForeground", "#cccccc"],
  ["--vscode-merge-commonContentBackground", "rgba(96, 96, 96, 0.16)"],
  ["--vscode-merge-commonHeaderBackground", "rgba(96, 96, 96, 0.4)"],
  ["--vscode-merge-currentContentBackground", "rgba(64, 200, 174, 0.2)"],
  ["--vscode-merge-currentHeaderBackground", "rgba(64, 200, 174, 0.5)"],
  ["--vscode-merge-incomingContentBackground", "rgba(64, 166, 255, 0.2)"],
  ["--vscode-merge-incomingHeaderBackground", "rgba(64, 166, 255, 0.5)"],
  ["--vscode-mergeEditor-change\.background", "rgba(155, 185, 85, 0.2)"],
  ["--vscode-mergeEditor-change\.word\.background", "rgba(156, 204, 44, 0.2)"],
  ["--vscode-mergeEditor-changeBase\.background", "#4b1818"],
  ["--vscode-mergeEditor-changeBase\.word\.background", "#6f1313"],
  ["--vscode-mergeEditor-conflict\.handled\.minimapOverViewRuler", "rgba(173, 172, 168, 0.93)"],
  ["--vscode-mergeEditor-conflict\.handledFocused\.border", "rgba(193, 193, 193, 0.8)"],
  ["--vscode-mergeEditor-conflict\.handledUnfocused\.border", "rgba(134, 134, 134, 0.29)"],
  ["--vscode-mergeEditor-conflict\.input1\.background", "rgba(64, 200, 174, 0.2)"],
  ["--vscode-mergeEditor-conflict\.input2\.background", "rgba(64, 166, 255, 0.2)"],
  ["--vscode-mergeEditor-conflict\.unhandled\.minimapOverViewRuler", "#fcba03"],
  ["--vscode-mergeEditor-conflict\.unhandledFocused\.border", "#ffa600"],
  ["--vscode-mergeEditor-conflict\.unhandledUnfocused\.border", "rgba(255, 166, 0, 0.48)"],
  ["--vscode-mergeEditor-conflictingLines\.background", "rgba(255, 234, 0, 0.28)"],
  ["--vscode-minimap-chatEditHighlight", "rgba(0, 43, 54, 0.6)"],
  ["--vscode-minimap-errorHighlight", "rgba(255, 18, 18, 0.7)"],
  ["--vscode-minimap-findMatchHighlight", "rgba(234, 92, 0, 0.33)"],
  ["--vscode-minimap-foregroundOpacity", "#000000"],
  ["--vscode-minimap-infoHighlight", "#59a4f9"],
  ["--vscode-minimap-selectionHighlight", "#274642"],
  ["--vscode-minimap-selectionOccurrenceHighlight", "rgba(0, 90, 111, 0.67)"],
  ["--vscode-minimap-warningHighlight", "#cca700"],
  ["--vscode-minimapGutter-addedBackground", "#487e02"],
  ["--vscode-minimapGutter-deletedBackground", "#f14c4c"],
  ["--vscode-minimapGutter-modifiedBackground", "#1b81a8"],
  ["--vscode-minimapSlider-activeBackground", "rgba(191, 191, 191, 0.2)"],
  ["--vscode-minimapSlider-background", "rgba(121, 121, 121, 0.2)"],
  ["--vscode-minimapSlider-hoverBackground", "rgba(100, 100, 100, 0.35)"],
  ["--vscode-multiDiffEditor-background", "#002b36"],
  ["--vscode-multiDiffEditor-headerBackground", "#262626"],
  ["--vscode-notebook-cellBorderColor", "rgba(0, 68, 84, 0.53)"],
  ["--vscode-notebook-cellEditorBackground", "#00212b"],
  ["--vscode-notebook-cellInsertionIndicator", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-notebook-cellStatusBarItemHoverBackground", "rgba(255, 255, 255, 0.15)"],
  ["--vscode-notebook-cellToolbarSeparator", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-notebook-editorBackground", "#002b36"],
  ["--vscode-notebook-focusedCellBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-notebook-focusedEditorBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-notebook-inactiveFocusedCellBorder", "rgba(0, 68, 84, 0.53)"],
  ["--vscode-notebook-selectedCellBackground", "rgba(0, 68, 84, 0.53)"],
  ["--vscode-notebook-selectedCellBorder", "rgba(0, 68, 84, 0.53)"],
  ["--vscode-notebook-symbolHighlightBackground", "rgba(255, 255, 255, 0.04)"],
  ["--vscode-notebookEditorOverviewRuler-runningCellForeground", "#89d185"],
  ["--vscode-notebookScrollbarSlider-activeBackground", "rgba(191, 191, 191, 0.4)"],
  ["--vscode-notebookScrollbarSlider-background", "rgba(121, 121, 121, 0.4)"],
  ["--vscode-notebookScrollbarSlider-hoverBackground", "rgba(100, 100, 100, 0.7)"],
  ["--vscode-notebookStatusErrorIcon-foreground", "#ffeaea"],
  ["--vscode-notebookStatusRunningIcon-foreground", "#cccccc"],
  ["--vscode-notebookStatusSuccessIcon-foreground", "#89d185"],
  ["--vscode-notificationCenterHeader-background", "#002b38"],
  ["--vscode-notificationLink-foreground", "#3794ff"],
  ["--vscode-notifications-background", "#00212b"],
  ["--vscode-notifications-border", "#002b38"],
  ["--vscode-notifications-foreground", "#cccccc"],
  ["--vscode-notificationsErrorIcon-foreground", "#f14c4c"],
  ["--vscode-notificationsInfoIcon-foreground", "#59a4f9"],
  ["--vscode-notificationsWarningIcon-foreground", "#cca700"],
  ["--vscode-panel-background", "#002b36"],
  ["--vscode-panel-border", "#2b2b4a"],
  ["--vscode-panel-dropBorder", "#e7e7e7"],
  ["--vscode-panelSection-border", "#2b2b4a"],
  ["--vscode-panelSection-dropBackground", "rgba(42, 161, 152, 0.27)"],
  ["--vscode-panelSectionHeader-background", "rgba(128, 128, 128, 0.2)"],
  ["--vscode-panelStickyScroll-background", "#002b36"],
  ["--vscode-panelStickyScroll-shadow", "#000000"],
  ["--vscode-panelTitle-activeBorder", "#e7e7e7"],
  ["--vscode-panelTitle-activeForeground", "#e7e7e7"],
  ["--vscode-panelTitle-inactiveForeground", "rgba(231, 231, 231, 0.6)"],
  ["--vscode-panelTitleBadge-background", "#007acc"],
  ["--vscode-panelTitleBadge-foreground", "#ffffff"],
  ["--vscode-peekView-border", "#2b2b4a"],
  ["--vscode-peekViewEditor-background", "#10192c"],
  ["--vscode-peekViewEditor-matchHighlightBackground", "rgba(119, 68, 170, 0.25)"],
  ["--vscode-peekViewEditorGutter-background", "#10192c"],
  ["--vscode-peekViewEditorStickyScroll-background", "#10192c"],
  ["--vscode-peekViewEditorStickyScrollGutter-background", "#10192c"],
  ["--vscode-peekViewResult-background", "#00212b"],
  ["--vscode-peekViewResult-fileForeground", "#ffffff"],
  ["--vscode-peekViewResult-lineForeground", "#bbbbbb"],
  ["--vscode-peekViewResult-matchHighlightBackground", "rgba(234, 92, 0, 0.3)"],
  ["--vscode-peekViewResult-selectionBackground", "rgba(51, 153, 255, 0.2)"],
  ["--vscode-peekViewResult-selectionForeground", "#ffffff"],
  ["--vscode-peekViewTitle-background", "#00212b"],
  ["--vscode-peekViewTitleDescription-foreground", "rgba(204, 204, 204, 0.7)"],
  ["--vscode-peekViewTitleLabel-foreground", "#ffffff"],
  ["--vscode-pickerGroup-border", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-pickerGroup-foreground", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-ports-iconRunningProcessForeground", "#369432"],
  ["--vscode-problemsErrorIcon-foreground", "#f14c4c"],
  ["--vscode-problemsInfoIcon-foreground", "#59a4f9"],
  ["--vscode-problemsWarningIcon-foreground", "#cca700"],
  ["--vscode-profileBadge-background", "#4d4d4d"],
  ["--vscode-profileBadge-foreground", "#ffffff"],
  ["--vscode-profiles-sashBorder", "#2b2b4a"],
  ["--vscode-progressBar-background", "#047aa6"],
  ["--vscode-quickInput-background", "#00212b"],
  ["--vscode-quickInput-foreground", "#cccccc"],
  ["--vscode-quickInputList-focusBackground", "#005a6f"],
  ["--vscode-quickInputList-focusForeground", "#ffffff"],
  ["--vscode-quickInputTitle-background", "rgba(255, 255, 255, 0.1)"],
  ["--vscode-radio-activeBackground", "rgba(42, 161, 152, 0.24)"],
  ["--vscode-radio-activeBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-radio-activeForeground", "#ffffff"],
  ["--vscode-radio-inactiveBorder", "rgba(255, 255, 255, 0.2)"],
  ["--vscode-radio-inactiveHoverBackground", "rgba(90, 93, 94, 0.5)"],
  ["--vscode-remoteHub-decorations\.addedForegroundColor", "#81b88b"],
  ["--vscode-remoteHub-decorations\.conflictForegroundColor", "#e4676b"],
  ["--vscode-remoteHub-decorations\.deletedForegroundColor", "#c74e39"],
  ["--vscode-remoteHub-decorations\.ignoredResourceForeground", "#8c8c8c"],
  ["--vscode-remoteHub-decorations\.incomingAddedForegroundColor", "#81b88b"],
  ["--vscode-remoteHub-decorations\.incomingDeletedForegroundColor", "#c74e39"],
  ["--vscode-remoteHub-decorations\.incomingModifiedForegroundColor", "#e2c08d"],
  ["--vscode-remoteHub-decorations\.incomingRenamedForegroundColor", "#73c991"],
  ["--vscode-remoteHub-decorations\.modifiedForegroundColor", "#e2c08d"],
  ["--vscode-remoteHub-decorations\.possibleConflictForegroundColor", "#cca700"],
  ["--vscode-remoteHub-decorations\.submoduleForegroundColor", "#8db9e2"],
  ["--vscode-remoteHub-decorations\.workspaceRepositoriesView\.hasUncommittedChangesForegroundColor", "#e2c08d"],
  ["--vscode-sash-hoverBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-scmGraph-foreground1", "#ffb000"],
  ["--vscode-scmGraph-foreground2", "#dc267f"],
  ["--vscode-scmGraph-foreground3", "#994f00"],
  ["--vscode-scmGraph-foreground4", "#40b0a6"],
  ["--vscode-scmGraph-foreground5", "#b66dff"],
  ["--vscode-scmGraph-historyItemBaseRefColor", "#ea5c00"],
  ["--vscode-scmGraph-historyItemHoverAdditionsForeground", "#81b88b"],
  ["--vscode-scmGraph-historyItemHoverDefaultLabelBackground", "#047aa6"],
  ["--vscode-scmGraph-historyItemHoverDefaultLabelForeground", "#cccccc"],
  ["--vscode-scmGraph-historyItemHoverDeletionsForeground", "#c74e39"],
  ["--vscode-scmGraph-historyItemHoverLabelForeground", "#002b36"],
  ["--vscode-scmGraph-historyItemRefColor", "#59a4f9"],
  ["--vscode-scmGraph-historyItemRemoteRefColor", "#b180d7"],
  ["--vscode-scrollbar-shadow", "#000000"],
  ["--vscode-scrollbarSlider-activeBackground", "rgba(191, 191, 191, 0.4)"],
  ["--vscode-scrollbarSlider-background", "rgba(121, 121, 121, 0.4)"],
  ["--vscode-scrollbarSlider-hoverBackground", "rgba(100, 100, 100, 0.7)"],
  ["--vscode-search-resultsInfoForeground", "rgba(204, 204, 204, 0.65)"],
  ["--vscode-searchEditor-findMatchBackground", "rgba(234, 92, 0, 0.22)"],
  ["--vscode-selection-background", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-settings-checkboxBackground", "#00212b"],
  ["--vscode-settings-checkboxBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-settings-checkboxForeground", "#f0f0f0"],
  ["--vscode-settings-dropdownBackground", "#00212b"],
  ["--vscode-settings-dropdownBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-settings-dropdownForeground", "#f0f0f0"],
  ["--vscode-settings-dropdownListBorder", "#454545"],
  ["--vscode-settings-focusedRowBackground", "rgba(0, 68, 84, 0.4)"],
  ["--vscode-settings-focusedRowBorder", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-settings-headerBorder", "#2b2b4a"],
  ["--vscode-settings-headerForeground", "#e7e7e7"],
  ["--vscode-settings-modifiedItemIndicator", "#0c7d9d"],
  ["--vscode-settings-numberInputBackground", "#003847"],
  ["--vscode-settings-numberInputForeground", "#93a1a1"],
  ["--vscode-settings-rowHoverBackground", "rgba(0, 68, 84, 0.2)"],
  ["--vscode-settings-sashBorder", "#2b2b4a"],
  ["--vscode-settings-settingsHeaderHoverForeground", "rgba(231, 231, 231, 0.7)"],
  ["--vscode-settings-textInputBackground", "#003847"],
  ["--vscode-settings-textInputForeground", "#93a1a1"],
  ["--vscode-sideBar-background", "#00212b"],
  ["--vscode-sideBar-dropBackground", "rgba(42, 161, 152, 0.27)"],
  ["--vscode-sideBarSectionHeader-background", "rgba(128, 128, 128, 0.2)"],
  ["--vscode-sideBarStickyScroll-background", "#00212b"],
  ["--vscode-sideBarStickyScroll-shadow", "#000000"],
  ["--vscode-sideBarTitle-background", "#00212b"],
  ["--vscode-sideBarTitle-foreground", "#93a1a1"],
  ["--vscode-sideBySideEditor-horizontalBorder", "#00212b"],
  ["--vscode-sideBySideEditor-verticalBorder", "#00212b"],
  ["--vscode-simpleFindWidget-sashBorder", "#454545"],
  ["--vscode-statusBar-background", "#00212b"],
  ["--vscode-statusBar-debuggingBackground", "#00212b"],
  ["--vscode-statusBar-debuggingForeground", "#93a1a1"],
  ["--vscode-statusBar-focusBorder", "#93a1a1"],
  ["--vscode-statusBar-foreground", "#93a1a1"],
  ["--vscode-statusBar-noFolderBackground", "#00212b"],
  ["--vscode-statusBar-noFolderForeground", "#93a1a1"],
  ["--vscode-statusBarItem-activeBackground", "rgba(255, 255, 255, 0.18)"],
  ["--vscode-statusBarItem-compactHoverBackground", "rgba(255, 255, 255, 0.12)"],
  ["--vscode-statusBarItem-errorBackground", "#ff2626"],
  ["--vscode-statusBarItem-errorForeground", "#ffffff"],
  ["--vscode-statusBarItem-errorHoverBackground", "rgba(255, 255, 255, 0.12)"],
  ["--vscode-statusBarItem-errorHoverForeground", "#93a1a1"],
  ["--vscode-statusBarItem-focusBorder", "#93a1a1"],
  ["--vscode-statusBarItem-hoverBackground", "rgba(255, 255, 255, 0.12)"],
  ["--vscode-statusBarItem-hoverForeground", "#93a1a1"],
  ["--vscode-statusBarItem-offlineBackground", "#6c1717"],
  ["--vscode-statusBarItem-offlineForeground", "#ffffff"],
  ["--vscode-statusBarItem-offlineHoverBackground", "rgba(255, 255, 255, 0.12)"],
  ["--vscode-statusBarItem-offlineHoverForeground", "#93a1a1"],
  ["--vscode-statusBarItem-prominentBackground", "#003847"],
  ["--vscode-statusBarItem-prominentForeground", "#93a1a1"],
  ["--vscode-statusBarItem-prominentHoverBackground", "#003847"],
  ["--vscode-statusBarItem-prominentHoverForeground", "#93a1a1"],
  ["--vscode-statusBarItem-remoteBackground", "rgba(42, 161, 152, 0.6)"],
  ["--vscode-statusBarItem-remoteForeground", "#ffffff"],
  ["--vscode-statusBarItem-remoteHoverBackground", "rgba(255, 255, 255, 0.12)"],
  ["--vscode-statusBarItem-remoteHoverForeground", "#93a1a1"],
  ["--vscode-statusBarItem-warningBackground", "#7a6400"],
  ["--vscode-statusBarItem-warningForeground", "#ffffff"],
  ["--vscode-statusBarItem-warningHoverBackground", "rgba(255, 255, 255, 0.12)"],
  ["--vscode-statusBarItem-warningHoverForeground", "#93a1a1"],
  ["--vscode-strokeThickness", "1px"],
  ["--vscode-symbolIcon-arrayForeground", "#cccccc"],
  ["--vscode-symbolIcon-booleanForeground", "#cccccc"],
  ["--vscode-symbolIcon-classForeground", "#ee9d28"],
  ["--vscode-symbolIcon-colorForeground", "#cccccc"],
  ["--vscode-symbolIcon-constantForeground", "#cccccc"],
  ["--vscode-symbolIcon-constructorForeground", "#b180d7"],
  ["--vscode-symbolIcon-enumeratorForeground", "#ee9d28"],
  ["--vscode-symbolIcon-enumeratorMemberForeground", "#75beff"],
  ["--vscode-symbolIcon-eventForeground", "#ee9d28"],
  ["--vscode-symbolIcon-fieldForeground", "#75beff"],
  ["--vscode-symbolIcon-fileForeground", "#cccccc"],
  ["--vscode-symbolIcon-folderForeground", "#cccccc"],
  ["--vscode-symbolIcon-functionForeground", "#b180d7"],
  ["--vscode-symbolIcon-interfaceForeground", "#75beff"],
  ["--vscode-symbolIcon-keyForeground", "#cccccc"],
  ["--vscode-symbolIcon-keywordForeground", "#cccccc"],
  ["--vscode-symbolIcon-methodForeground", "#b180d7"],
  ["--vscode-symbolIcon-moduleForeground", "#cccccc"],
  ["--vscode-symbolIcon-namespaceForeground", "#cccccc"],
  ["--vscode-symbolIcon-nullForeground", "#cccccc"],
  ["--vscode-symbolIcon-numberForeground", "#cccccc"],
  ["--vscode-symbolIcon-objectForeground", "#cccccc"],
  ["--vscode-symbolIcon-operatorForeground", "#cccccc"],
  ["--vscode-symbolIcon-packageForeground", "#cccccc"],
  ["--vscode-symbolIcon-propertyForeground", "#cccccc"],
  ["--vscode-symbolIcon-referenceForeground", "#cccccc"],
  ["--vscode-symbolIcon-snippetForeground", "#cccccc"],
  ["--vscode-symbolIcon-stringForeground", "#cccccc"],
  ["--vscode-symbolIcon-structForeground", "#cccccc"],
  ["--vscode-symbolIcon-textForeground", "#cccccc"],
  ["--vscode-symbolIcon-typeParameterForeground", "#cccccc"],
  ["--vscode-symbolIcon-unitForeground", "#cccccc"],
  ["--vscode-symbolIcon-variableForeground", "#75beff"],
  ["--vscode-tab-activeBackground", "#002b37"],
  ["--vscode-tab-activeForeground", "#d6dbdb"],
  ["--vscode-tab-activeModifiedBorder", "#3399cc"],
  ["--vscode-tab-border", "#003847"],
  ["--vscode-tab-dragAndDropBorder", "#d6dbdb"],
  ["--vscode-tab-inactiveBackground", "#004052"],
  ["--vscode-tab-inactiveForeground", "#93a1a1"],
  ["--vscode-tab-inactiveModifiedBorder", "rgba(51, 153, 204, 0.5)"],
  ["--vscode-tab-lastPinnedBorder", "rgba(42, 161, 152, 0.27)"],
  ["--vscode-tab-selectedBackground", "#002b37"],
  ["--vscode-tab-selectedForeground", "#d6dbdb"],
  ["--vscode-tab-unfocusedActiveBackground", "#002b37"],
  ["--vscode-tab-unfocusedActiveForeground", "rgba(214, 219, 219, 0.5)"],
  ["--vscode-tab-unfocusedActiveModifiedBorder", "rgba(51, 153, 204, 0.5)"],
  ["--vscode-tab-unfocusedInactiveBackground", "#004052"],
  ["--vscode-tab-unfocusedInactiveForeground", "rgba(147, 161, 161, 0.5)"],
  ["--vscode-tab-unfocusedInactiveModifiedBorder", "rgba(51, 153, 204, 0.25)"],
  ["--vscode-terminal-ansiBlack", "#073642"],
  ["--vscode-terminal-ansiBlue", "#268bd2"],
  ["--vscode-terminal-ansiBrightBlack", "#002b36"],
  ["--vscode-terminal-ansiBrightBlue", "#839496"],
  ["--vscode-terminal-ansiBrightCyan", "#93a1a1"],
  ["--vscode-terminal-ansiBrightGreen", "#586e75"],
  ["--vscode-terminal-ansiBrightMagenta", "#6c71c4"],
  ["--vscode-terminal-ansiBrightRed", "#cb4b16"],
  ["--vscode-terminal-ansiBrightWhite", "#fdf6e3"],
  ["--vscode-terminal-ansiBrightYellow", "#657b83"],
  ["--vscode-terminal-ansiCyan", "#2aa198"],
  ["--vscode-terminal-ansiGreen", "#859900"],
  ["--vscode-terminal-ansiMagenta", "#d33682"],
  ["--vscode-terminal-ansiRed", "#dc322f"],
  ["--vscode-terminal-ansiWhite", "#eee8d5"],
  ["--vscode-terminal-ansiYellow", "#b58900"],
  ["--vscode-terminal-border", "#2b2b4a"],
  ["--vscode-terminal-dropBackground", "rgba(42, 161, 152, 0.27)"],
  ["--vscode-terminal-findMatchBackground", "#515c6a"],
  ["--vscode-terminal-findMatchHighlightBackground", "rgba(234, 92, 0, 0.33)"],
  ["--vscode-terminal-foreground", "#cccccc"],
  ["--vscode-terminal-hoverHighlightBackground", "rgba(38, 79, 120, 0.13)"],
  ["--vscode-terminal-inactiveSelectionBackground", "rgba(39, 70, 66, 0.5)"],
  ["--vscode-terminal-initialHintForeground", "rgba(255, 255, 255, 0.34)"],
  ["--vscode-terminal-selectionBackground", "#274642"],
  ["--vscode-terminalCommandDecoration-defaultBackground", "rgba(255, 255, 255, 0.25)"],
  ["--vscode-terminalCommandDecoration-errorBackground", "#f14c4c"],
  ["--vscode-terminalCommandDecoration-successBackground", "#1b81a8"],
  ["--vscode-terminalCommandGuide-foreground", "rgba(0, 68, 84, 0.53)"],
  ["--vscode-terminalOverviewRuler-border", "rgba(127, 127, 127, 0.3)"],
  ["--vscode-terminalOverviewRuler-cursorForeground", "rgba(160, 160, 160, 0.8)"],
  ["--vscode-terminalOverviewRuler-findMatchForeground", "rgba(209, 134, 22, 0.49)"],
  ["--vscode-terminalStickyScrollHover-background", "#2a2d2e"],
  ["--vscode-terminalSymbolIcon-aliasForeground", "#b180d7"],
  ["--vscode-terminalSymbolIcon-argumentForeground", "#75beff"],
  ["--vscode-terminalSymbolIcon-branchForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-commitForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-fileForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-flagForeground", "#ee9d28"],
  ["--vscode-terminalSymbolIcon-folderForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-methodForeground", "#b180d7"],
  ["--vscode-terminalSymbolIcon-optionForeground", "#ee9d28"],
  ["--vscode-terminalSymbolIcon-optionValueForeground", "#75beff"],
  ["--vscode-terminalSymbolIcon-pullRequestDoneForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-pullRequestForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-remoteForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-stashForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-symbolicLinkFileForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-symbolicLinkFolderForeground", "#cccccc"],
  ["--vscode-terminalSymbolIcon-symbolText", "#cccccc"],
  ["--vscode-terminalSymbolIcon-tagForeground", "#cccccc"],
  ["--vscode-testing-coverCountBadgeBackground", "#047aa6"],
  ["--vscode-testing-coverCountBadgeForeground", "#ffffff"],
  ["--vscode-testing-coveredBackground", "rgba(156, 204, 44, 0.2)"],
  ["--vscode-testing-coveredBorder", "rgba(156, 204, 44, 0.15)"],
  ["--vscode-testing-coveredGutterBackground", "rgba(156, 204, 44, 0.12)"],
  ["--vscode-testing-iconErrored", "#f14c4c"],
  ["--vscode-testing-iconErrored\.retired", "rgba(241, 76, 76, 0.7)"],
  ["--vscode-testing-iconFailed", "#f14c4c"],
  ["--vscode-testing-iconFailed\.retired", "rgba(241, 76, 76, 0.7)"],
  ["--vscode-testing-iconPassed", "#73c991"],
  ["--vscode-testing-iconPassed\.retired", "rgba(115, 201, 145, 0.7)"],
  ["--vscode-testing-iconQueued", "#cca700"],
  ["--vscode-testing-iconQueued\.retired", "rgba(204, 167, 0, 0.7)"],
  ["--vscode-testing-iconSkipped", "#848484"],
  ["--vscode-testing-iconSkipped\.retired", "rgba(132, 132, 132, 0.7)"],
  ["--vscode-testing-iconUnset", "#848484"],
  ["--vscode-testing-iconUnset\.retired", "rgba(132, 132, 132, 0.7)"],
  ["--vscode-testing-message\.error\.badgeBackground", "#f14c4c"],
  ["--vscode-testing-message\.error\.badgeBorder", "#f14c4c"],
  ["--vscode-testing-message\.error\.badgeForeground", "#000000"],
  ["--vscode-testing-message\.info\.decorationForeground", "rgba(131, 148, 150, 0.5)"],
  ["--vscode-testing-messagePeekBorder", "#59a4f9"],
  ["--vscode-testing-messagePeekHeaderBackground", "rgba(89, 164, 249, 0.1)"],
  ["--vscode-testing-peekBorder", "#f14c4c"],
  ["--vscode-testing-peekHeaderBackground", "rgba(241, 76, 76, 0.1)"],
  ["--vscode-testing-runAction", "#73c991"],
  ["--vscode-testing-uncoveredBackground", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-testing-uncoveredBorder", "rgba(255, 0, 0, 0.15)"],
  ["--vscode-testing-uncoveredBranchBackground", "#661920"],
  ["--vscode-testing-uncoveredGutterBackground", "rgba(255, 0, 0, 0.3)"],
  ["--vscode-textBlockQuote-background", "#222222"],
  ["--vscode-textBlockQuote-border", "rgba(0, 122, 204, 0.5)"],
  ["--vscode-textCodeBlock-background", "rgba(10, 10, 10, 0.4)"],
  ["--vscode-textLink-activeForeground", "#3794ff"],
  ["--vscode-textLink-foreground", "#3794ff"],
  ["--vscode-textPreformat-background", "rgba(255, 255, 255, 0.1)"],
  ["--vscode-textPreformat-foreground", "#d7ba7d"],
  ["--vscode-textSeparator-foreground", "rgba(255, 255, 255, 0.18)"],
  ["--vscode-titleBar-activeBackground", "#002c39"],
  ["--vscode-titleBar-activeForeground", "#cccccc"],
  ["--vscode-titleBar-inactiveBackground", "rgba(0, 44, 57, 0.6)"],
  ["--vscode-titleBar-inactiveForeground", "rgba(204, 204, 204, 0.6)"],
  ["--vscode-toolbar-activeBackground", "rgba(99, 102, 103, 0.31)"],
  ["--vscode-toolbar-hoverBackground", "rgba(90, 93, 94, 0.31)"],
  ["--vscode-tree-inactiveIndentGuidesStroke", "rgba(88, 88, 88, 0.4)"],
  ["--vscode-tree-indentGuidesStroke", "#585858"],
  ["--vscode-tree-tableColumnsBorder", "rgba(204, 204, 204, 0.13)"],
  ["--vscode-tree-tableOddRowsBackground", "rgba(204, 204, 204, 0.04)"],
  ["--vscode-walkThrough-embeddedEditorBackground", "rgba(0, 0, 0, 0.4)"],
  ["--vscode-walkthrough-stepTitle\.foreground", "#ffffff"],
  ["--vscode-welcomePage-progress\.background", "#003847"],
  ["--vscode-welcomePage-progress\.foreground", "#3794ff"],
  ["--vscode-welcomePage-tileBackground", "#00212b"],
  ["--vscode-welcomePage-tileBorder", "rgba(255, 255, 255, 0.1)"],
  ["--vscode-welcomePage-tileHoverBackground", "#002734"],
  ["--vscode-widget-shadow", "rgba(0, 0, 0, 0.36)"],
];
