/** @type {[string, string][]} */
export const theme = [
  ["--vscode-actionBar-toggledBackground", "rgba(151, 105, 220, 0.2)"],
  ["--vscode-activityBar-activeBorder", "#705697"],
  ["--vscode-activityBar-background", "#ededf5"],
  ["--vscode-activityBar-dropBorder", "#705697"],
  ["--vscode-activityBar-foreground", "#705697"],
  ["--vscode-activityBar-inactiveForeground", "rgba(112, 86, 151, 0.4)"],
  ["--vscode-activityBarBadge-background", "#705697"],
  ["--vscode-activityBarBadge-foreground", "#ffffff"],
  ["--vscode-activityBarTop-activeBorder", "#424242"],
  ["--vscode-activityBarTop-dropBorder", "#424242"],
  ["--vscode-activityBarTop-foreground", "#424242"],
  ["--vscode-activityBarTop-inactiveForeground", "rgba(66, 66, 66, 0.75)"],
  ["--vscode-activityErrorBadge-background", "#e51400"],
  ["--vscode-activityErrorBadge-foreground", "#ffffff"],
  ["--vscode-activityWarningBadge-background", "#b27c00"],
  ["--vscode-activityWarningBadge-foreground", "#ffffff"],
  ["--vscode-agentSessionReadIndicator-foreground", "rgba(97, 97, 97, 0.2)"],
  ["--vscode-agentSessionSelectedBadge-border", "rgba(108, 108, 108, 0.3)"],
  ["--vscode-agentSessionSelectedUnfocusedBadge-border", "rgba(97, 97, 97, 0.3)"],
  ["--vscode-agentStatusIndicator-background", "rgba(0, 0, 0, 0.05)"],
  ["--vscode-aiCustomizationManagement-sashBorder", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-badge-background", "rgba(112, 86, 151, 0.67)"],
  ["--vscode-badge-foreground", "#333333"],
  ["--vscode-banner-background", "#89b262"],
  ["--vscode-banner-foreground", "#6c6c6c"],
  ["--vscode-banner-iconForeground", "#0063d3"],
  ["--vscode-bodyFontSize", "13px"],
  ["--vscode-bodyFontSize-small", "12px"],
  ["--vscode-bodyFontSize-xSmall", "11px"],
  ["--vscode-breadcrumb-activeSelectionForeground", "#4e4e4e"],
  ["--vscode-breadcrumb-background", "#f5f5f5"],
  ["--vscode-breadcrumb-focusForeground", "#4e4e4e"],
  ["--vscode-breadcrumb-foreground", "rgba(97, 97, 97, 0.8)"],
  ["--vscode-breadcrumbPicker-background", "#f3f3f3"],
  ["--vscode-browser-border", "#f3f3f3"],
  ["--vscode-button-background", "#705697"],
  ["--vscode-button-foreground", "#ffffff"],
  ["--vscode-button-hoverBackground", "#5a4579"],
  ["--vscode-button-secondaryBackground", "#e0e0e0"],
  ["--vscode-button-secondaryForeground", "#616161"],
  ["--vscode-button-secondaryHoverBackground", "#ffffff"],
  ["--vscode-button-separator", "rgba(255, 255, 255, 0.4)"],
  ["--vscode-chart-axis", "rgba(0, 0, 0, 0.6)"],
  ["--vscode-chart-guide", "rgba(0, 0, 0, 0.2)"],
  ["--vscode-chart-line", "#236b8e"],
  ["--vscode-charts-blue", "#0063d3"],
  ["--vscode-charts-foreground", "#616161"],
  ["--vscode-charts-green", "#388a34"],
  ["--vscode-charts-lines", "rgba(97, 97, 97, 0.5)"],
  ["--vscode-charts-orange", "rgba(237, 201, 216, 0.6)"],
  ["--vscode-charts-purple", "#652d90"],
  ["--vscode-charts-red", "#e51400"],
  ["--vscode-charts-yellow", "#bf8803"],
  ["--vscode-chat-avatarBackground", "#f2f2f2"],
  ["--vscode-chat-avatarForeground", "#616161"],
  ["--vscode-chat-checkpointSeparator", "#a9a9a9"],
  ["--vscode-chat-editedFileForeground", "#895503"],
  ["--vscode-chat-linesAddedForeground", "#107c10"],
  ["--vscode-chat-linesRemovedForeground", "#bc2f32"],
  ["--vscode-chat-requestBackground", "rgba(245, 245, 245, 0.62)"],
  ["--vscode-chat-requestBorder", "rgba(0, 0, 0, 0.1)"],
  ["--vscode-chat-requestBubbleBackground", "rgba(201, 208, 217, 0.3)"],
  ["--vscode-chat-requestBubbleHoverBackground", "rgba(201, 208, 217, 0.6)"],
  ["--vscode-chat-requestCodeBorder", "rgba(14, 99, 156, 0.25)"],
  ["--vscode-chat-slashCommandBackground", "rgba(173, 206, 255, 0.48)"],
  ["--vscode-chat-slashCommandForeground", "#26569e"],
  ["--vscode-chat-thinkingShimmer", "#000000"],
  ["--vscode-chatManagement-sashBorder", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-checkbox-background", "#f5f5f5"],
  ["--vscode-checkbox-border", "#cecece"],
  ["--vscode-checkbox-disabled\.background", "#c4c4c4"],
  ["--vscode-checkbox-disabled\.foreground", "#919191"],
  ["--vscode-checkbox-foreground", "#616161"],
  ["--vscode-checkbox-selectBackground", "#f3f3f3"],
  ["--vscode-checkbox-selectBorder", "#424242"],
  ["--vscode-codiconFontSize", "16px"],
  ["--vscode-commandCenter-activeBackground", "rgba(0, 0, 0, 0.08)"],
  ["--vscode-commandCenter-activeBorder", "rgba(51, 51, 51, 0.3)"],
  ["--vscode-commandCenter-activeForeground", "#333333"],
  ["--vscode-commandCenter-background", "rgba(0, 0, 0, 0.05)"],
  ["--vscode-commandCenter-border", "rgba(51, 51, 51, 0.2)"],
  ["--vscode-commandCenter-debuggingBackground", "rgba(112, 86, 151, 0.26)"],
  ["--vscode-commandCenter-foreground", "#333333"],
  ["--vscode-commandCenter-inactiveBorder", "rgba(51, 51, 51, 0.15)"],
  ["--vscode-commandCenter-inactiveForeground", "rgba(51, 51, 51, 0.6)"],
  ["--vscode-commentsView-resolvedIcon", "rgba(97, 97, 97, 0.5)"],
  ["--vscode-commentsView-unresolvedIcon", "#9769dc"],
  ["--vscode-cornerRadius-circle", "9999px"],
  ["--vscode-cornerRadius-large", "8px"],
  ["--vscode-cornerRadius-medium", "6px"],
  ["--vscode-cornerRadius-small", "4px"],
  ["--vscode-cornerRadius-xLarge", "12px"],
  ["--vscode-cornerRadius-xSmall", "2px"],
  ["--vscode-debugConsole-errorForeground", "#f1897f"],
  ["--vscode-debugConsole-infoForeground", "#0063d3"],
  ["--vscode-debugConsole-sourceForeground", "#616161"],
  ["--vscode-debugConsole-warningForeground", "#bf8803"],
  ["--vscode-debugConsoleInputIcon-foreground", "#616161"],
  ["--vscode-debugExceptionWidget-background", "#f1dfde"],
  ["--vscode-debugExceptionWidget-border", "#a31515"],
  ["--vscode-debugIcon-breakpointCurrentStackframeForeground", "#be8700"],
  ["--vscode-debugIcon-breakpointDisabledForeground", "#848484"],
  ["--vscode-debugIcon-breakpointForeground", "#e51400"],
  ["--vscode-debugIcon-breakpointStackframeForeground", "#89d185"],
  ["--vscode-debugIcon-breakpointUnverifiedForeground", "#848484"],
  ["--vscode-debugIcon-continueForeground", "#007acc"],
  ["--vscode-debugIcon-disconnectForeground", "#a1260d"],
  ["--vscode-debugIcon-pauseForeground", "#007acc"],
  ["--vscode-debugIcon-restartForeground", "#388a34"],
  ["--vscode-debugIcon-startForeground", "#388a34"],
  ["--vscode-debugIcon-stepBackForeground", "#007acc"],
  ["--vscode-debugIcon-stepIntoForeground", "#007acc"],
  ["--vscode-debugIcon-stepOutForeground", "#007acc"],
  ["--vscode-debugIcon-stepOverForeground", "#007acc"],
  ["--vscode-debugIcon-stopForeground", "#a1260d"],
  ["--vscode-debugTokenExpression-boolean", "#0000ff"],
  ["--vscode-debugTokenExpression-error", "#e51400"],
  ["--vscode-debugTokenExpression-name", "#9b46b0"],
  ["--vscode-debugTokenExpression-number", "#098658"],
  ["--vscode-debugTokenExpression-string", "#a31515"],
  ["--vscode-debugTokenExpression-type", "#4a90e2"],
  ["--vscode-debugTokenExpression-value", "rgba(108, 108, 108, 0.8)"],
  ["--vscode-debugToolBar-background", "#f3f3f3"],
  ["--vscode-debugView-exceptionLabelBackground", "#a31515"],
  ["--vscode-debugView-exceptionLabelForeground", "#ffffff"],
  ["--vscode-debugView-stateLabelBackground", "rgba(136, 136, 136, 0.27)"],
  ["--vscode-debugView-stateLabelForeground", "#616161"],
  ["--vscode-debugView-valueChangedHighlight", "#569cd6"],
  ["--vscode-descriptionForeground", "#717171"],
  ["--vscode-diffEditor-diagonalFill", "rgba(34, 34, 34, 0.2)"],
  ["--vscode-diffEditor-insertedLineBackground", "rgba(155, 185, 85, 0.2)"],
  ["--vscode-diffEditor-insertedTextBackground", "rgba(156, 204, 44, 0.25)"],
  ["--vscode-diffEditor-move\.border", "rgba(139, 139, 139, 0.61)"],
  ["--vscode-diffEditor-moveActive\.border", "#ffa500"],
  ["--vscode-diffEditor-removedLineBackground", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-diffEditor-removedTextBackground", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-diffEditor-unchangedCodeBackground", "rgba(184, 184, 184, 0.16)"],
  ["--vscode-diffEditor-unchangedRegionBackground", "#f2f2f2"],
  ["--vscode-diffEditor-unchangedRegionForeground", "#616161"],
  ["--vscode-diffEditor-unchangedRegionShadow", "rgba(115, 115, 115, 0.75)"],
  ["--vscode-disabledForeground", "rgba(97, 97, 97, 0.5)"],
  ["--vscode-dropdown-background", "#f5f5f5"],
  ["--vscode-dropdown-border", "#cecece"],
  ["--vscode-dropdown-foreground", "#616161"],
  ["--vscode-editor-background", "#f5f5f5"],
  ["--vscode-editor-compositionBorder", "#000000"],
  ["--vscode-editor-findMatchBackground", "#bf9cac"],
  ["--vscode-editor-findMatchHighlightBackground", "rgba(237, 201, 216, 0.6)"],
  ["--vscode-editor-findRangeHighlightBackground", "rgba(180, 180, 180, 0.3)"],
  ["--vscode-editor-focusedStackFrameHighlightBackground", "rgba(206, 231, 206, 0.45)"],
  ["--vscode-editor-foldBackground", "rgba(201, 208, 217, 0.3)"],
  ["--vscode-editor-foldPlaceholderForeground", "#808080"],
  ["--vscode-editor-font-feature-settings", "\"liga\" off, \"calt\" off"],
  ["--vscode-editor-font-size", "14px"],
  ["--vscode-editor-font-weight", "normal"],
  ["--vscode-editor-foreground", "#333333"],
  ["--vscode-editor-hoverHighlightBackground", "rgba(173, 214, 255, 0.15)"],
  ["--vscode-editor-inactiveLineHighlightBackground", "#e4f6d4"],
  ["--vscode-editor-inactiveSelectionBackground", "rgba(201, 208, 217, 0.5)"],
  ["--vscode-editor-inlineValuesBackground", "rgba(255, 200, 0, 0.2)"],
  ["--vscode-editor-inlineValuesForeground", "rgba(0, 0, 0, 0.5)"],
  ["--vscode-editor-lineHighlightBackground", "#e4f6d4"],
  ["--vscode-editor-lineHighlightBorder", "#eeeeee"],
  ["--vscode-editor-linkedEditingBackground", "rgba(255, 0, 0, 0.3)"],
  ["--vscode-editor-placeholder\.foreground", "rgba(0, 0, 0, 0.47)"],
  ["--vscode-editor-rangeHighlightBackground", "rgba(253, 255, 0, 0.2)"],
  ["--vscode-editor-selectionBackground", "#c9d0d9"],
  ["--vscode-editor-selectionHighlightBackground", "rgba(224, 228, 234, 0.6)"],
  ["--vscode-editor-snippetFinalTabstopHighlightBorder", "rgba(10, 50, 100, 0.5)"],
  ["--vscode-editor-snippetTabstopHighlightBackground", "rgba(10, 50, 100, 0.2)"],
  ["--vscode-editor-stackFrameHighlightBackground", "rgba(255, 255, 102, 0.45)"],
  ["--vscode-editor-symbolHighlightBackground", "rgba(237, 201, 216, 0.6)"],
  ["--vscode-editor-wordHighlightBackground", "rgba(87, 87, 87, 0.25)"],
  ["--vscode-editor-wordHighlightStrongBackground", "rgba(14, 99, 156, 0.25)"],
  ["--vscode-editor-wordHighlightTextBackground", "rgba(87, 87, 87, 0.25)"],
  ["--vscode-editorActionList-background", "#f3f3f3"],
  ["--vscode-editorActionList-focusBackground", "#c4d9b1"],
  ["--vscode-editorActionList-focusForeground", "#6c6c6c"],
  ["--vscode-editorActionList-foreground", "#616161"],
  ["--vscode-editorActiveLineNumber-foreground", "#0b216f"],
  ["--vscode-editorBracketHighlight-foreground1", "#0431fa"],
  ["--vscode-editorBracketHighlight-foreground2", "#319331"],
  ["--vscode-editorBracketHighlight-foreground3", "#7b3814"],
  ["--vscode-editorBracketHighlight-foreground4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketHighlight-foreground5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketHighlight-foreground6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketHighlight-unexpectedBracket\.foreground", "rgba(255, 18, 18, 0.8)"],
  ["--vscode-editorBracketMatch-background", "rgba(0, 100, 0, 0.1)"],
  ["--vscode-editorBracketMatch-border", "#b9b9b9"],
  ["--vscode-editorBracketPairGuide-activeBackground1", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground2", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground3", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-activeBackground6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background1", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background2", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background3", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorBracketPairGuide-background6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorCodeLens-foreground", "#919191"],
  ["--vscode-editorCommentsWidget-rangeActiveBackground", "rgba(151, 105, 220, 0.1)"],
  ["--vscode-editorCommentsWidget-rangeBackground", "rgba(151, 105, 220, 0.1)"],
  ["--vscode-editorCommentsWidget-replyInputBackground", "#f2f8fc"],
  ["--vscode-editorCommentsWidget-resolvedBorder", "rgba(97, 97, 97, 0.5)"],
  ["--vscode-editorCommentsWidget-unresolvedBorder", "#9769dc"],
  ["--vscode-editorCursor-foreground", "#54494b"],
  ["--vscode-editorError-foreground", "#e51400"],
  ["--vscode-editorGhostText-foreground", "rgba(0, 0, 0, 0.47)"],
  ["--vscode-editorGroup-border", "#e7e7e7"],
  ["--vscode-editorGroup-dropBackground", "rgba(201, 208, 217, 0.53)"],
  ["--vscode-editorGroup-dropIntoPromptBackground", "#f3f3f3"],
  ["--vscode-editorGroup-dropIntoPromptForeground", "#616161"],
  ["--vscode-editorGroupHeader-noTabsBackground", "#f5f5f5"],
  ["--vscode-editorGroupHeader-tabsBackground", "#f3f3f3"],
  ["--vscode-editorGutter-addedBackground", "#48985d"],
  ["--vscode-editorGutter-addedSecondaryBackground", "#a7d5b3"],
  ["--vscode-editorGutter-background", "#f5f5f5"],
  ["--vscode-editorGutter-commentDraftGlyphForeground", "#333333"],
  ["--vscode-editorGutter-commentGlyphForeground", "#333333"],
  ["--vscode-editorGutter-commentRangeForeground", "#c8d2c0"],
  ["--vscode-editorGutter-commentUnresolvedGlyphForeground", "#333333"],
  ["--vscode-editorGutter-deletedBackground", "#e51400"],
  ["--vscode-editorGutter-deletedSecondaryBackground", "#ff3d2b"],
  ["--vscode-editorGutter-foldingControlForeground", "#424242"],
  ["--vscode-editorGutter-itemBackground", "#c8d2c0"],
  ["--vscode-editorGutter-itemGlyphForeground", "#333333"],
  ["--vscode-editorGutter-modifiedBackground", "#2090d3"],
  ["--vscode-editorGutter-modifiedSecondaryBackground", "#aad8f2"],
  ["--vscode-editorHint-foreground", "#6c6c6c"],
  ["--vscode-editorHoverWidget-background", "#f3f3f3"],
  ["--vscode-editorHoverWidget-border", "#c8c8c8"],
  ["--vscode-editorHoverWidget-foreground", "#616161"],
  ["--vscode-editorHoverWidget-highlightForeground", "#9769dc"],
  ["--vscode-editorHoverWidget-statusBarBackground", "#e7e7e7"],
  ["--vscode-editorIndentGuide-activeBackground", "rgba(119, 119, 119, 0.69)"],
  ["--vscode-editorIndentGuide-activeBackground1", "rgba(119, 119, 119, 0.69)"],
  ["--vscode-editorIndentGuide-activeBackground2", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-activeBackground3", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-activeBackground4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-activeBackground5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-activeBackground6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background", "rgba(170, 170, 170, 0.38)"],
  ["--vscode-editorIndentGuide-background1", "rgba(170, 170, 170, 0.38)"],
  ["--vscode-editorIndentGuide-background2", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background3", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background4", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background5", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorIndentGuide-background6", "rgba(0, 0, 0, 0)"],
  ["--vscode-editorInfo-foreground", "#0063d3"],
  ["--vscode-editorInlayHint-background", "rgba(112, 86, 151, 0.07)"],
  ["--vscode-editorInlayHint-foreground", "#969696"],
  ["--vscode-editorInlayHint-parameterBackground", "rgba(112, 86, 151, 0.07)"],
  ["--vscode-editorInlayHint-parameterForeground", "#969696"],
  ["--vscode-editorInlayHint-typeBackground", "rgba(112, 86, 151, 0.07)"],
  ["--vscode-editorInlayHint-typeForeground", "#969696"],
  ["--vscode-editorLightBulb-foreground", "#ddb100"],
  ["--vscode-editorLightBulbAi-foreground", "#ddb100"],
  ["--vscode-editorLightBulbAutoFix-foreground", "#007acc"],
  ["--vscode-editorLineNumber-activeForeground", "#9769dc"],
  ["--vscode-editorLineNumber-foreground", "#6d705b"],
  ["--vscode-editorLink-activeForeground", "#0000ff"],
  ["--vscode-editorMarkerNavigation-background", "#f5f5f5"],
  ["--vscode-editorMarkerNavigationError-background", "#e51400"],
  ["--vscode-editorMarkerNavigationError-headerBackground", "rgba(229, 20, 0, 0.1)"],
  ["--vscode-editorMarkerNavigationInfo-background", "#0063d3"],
  ["--vscode-editorMarkerNavigationInfo-headerBackground", "rgba(0, 99, 211, 0.1)"],
  ["--vscode-editorMarkerNavigationWarning-background", "#bf8803"],
  ["--vscode-editorMarkerNavigationWarning-headerBackground", "rgba(191, 136, 3, 0.1)"],
  ["--vscode-editorMinimap-inlineChatInserted", "rgba(156, 204, 44, 0.2)"],
  ["--vscode-editorMultiCursor-primary\.foreground", "#54494b"],
  ["--vscode-editorMultiCursor-secondary\.foreground", "#54494b"],
  ["--vscode-editorOverviewRuler-addedForeground", "rgba(72, 152, 93, 0.6)"],
  ["--vscode-editorOverviewRuler-border", "rgba(127, 127, 127, 0.3)"],
  ["--vscode-editorOverviewRuler-bracketMatchForeground", "#a0a0a0"],
  ["--vscode-editorOverviewRuler-commentDraftForeground", "#c8d2c0"],
  ["--vscode-editorOverviewRuler-commentForeground", "#c8d2c0"],
  ["--vscode-editorOverviewRuler-commentUnresolvedForeground", "#c8d2c0"],
  ["--vscode-editorOverviewRuler-commonContentForeground", "rgba(96, 96, 96, 0.4)"],
  ["--vscode-editorOverviewRuler-currentContentForeground", "rgba(64, 200, 174, 0.5)"],
  ["--vscode-editorOverviewRuler-deletedForeground", "rgba(229, 20, 0, 0.6)"],
  ["--vscode-editorOverviewRuler-errorForeground", "rgba(255, 18, 18, 0.7)"],
  ["--vscode-editorOverviewRuler-findMatchForeground", "rgba(209, 134, 22, 0.49)"],
  ["--vscode-editorOverviewRuler-incomingContentForeground", "rgba(64, 166, 255, 0.5)"],
  ["--vscode-editorOverviewRuler-infoForeground", "#0063d3"],
  ["--vscode-editorOverviewRuler-inlineChatInserted", "rgba(156, 204, 44, 0.2)"],
  ["--vscode-editorOverviewRuler-inlineChatRemoved", "rgba(255, 0, 0, 0.16)"],
  ["--vscode-editorOverviewRuler-modifiedForeground", "rgba(32, 144, 211, 0.6)"],
  ["--vscode-editorOverviewRuler-rangeHighlightForeground", "rgba(0, 122, 204, 0.6)"],
  ["--vscode-editorOverviewRuler-selectionHighlightForeground", "rgba(160, 160, 160, 0.8)"],
  ["--vscode-editorOverviewRuler-warningForeground", "#bf8803"],
  ["--vscode-editorOverviewRuler-wordHighlightForeground", "rgba(160, 160, 160, 0.8)"],
  ["--vscode-editorOverviewRuler-wordHighlightStrongForeground", "rgba(192, 160, 192, 0.8)"],
  ["--vscode-editorOverviewRuler-wordHighlightTextForeground", "rgba(160, 160, 160, 0.8)"],
  ["--vscode-editorPane-background", "#f5f5f5"],
  ["--vscode-editorRuler-foreground", "#d3d3d3"],
  ["--vscode-editorStickyScroll-background", "#f5f5f5"],
  ["--vscode-editorStickyScroll-shadow", "#dddddd"],
  ["--vscode-editorStickyScrollGutter-background", "#f5f5f5"],
  ["--vscode-editorStickyScrollHover-background", "#f0f0f0"],
  ["--vscode-editorSuggestWidget-background", "#f3f3f3"],
  ["--vscode-editorSuggestWidget-border", "#c8c8c8"],
  ["--vscode-editorSuggestWidget-focusHighlightForeground", "#9769dc"],
  ["--vscode-editorSuggestWidget-foreground", "#333333"],
  ["--vscode-editorSuggestWidget-highlightForeground", "#9769dc"],
  ["--vscode-editorSuggestWidget-selectedBackground", "#cadeb9"],
  ["--vscode-editorSuggestWidget-selectedForeground", "#6c6c6c"],
  ["--vscode-editorSuggestWidgetStatus-foreground", "rgba(51, 51, 51, 0.5)"],
  ["--vscode-editorUnicodeHighlight-border", "#bf8803"],
  ["--vscode-editorUnnecessaryCode-opacity", "rgba(0, 0, 0, 0.47)"],
  ["--vscode-editorWarning-foreground", "#bf8803"],
  ["--vscode-editorWhitespace-foreground", "#aaaaaa"],
  ["--vscode-editorWidget-background", "#f3f3f3"],
  ["--vscode-editorWidget-border", "#c8c8c8"],
  ["--vscode-editorWidget-foreground", "#616161"],
  ["--vscode-errorForeground", "#f1897f"],
  ["--vscode-extensionBadge-remoteBackground", "#705697"],
  ["--vscode-extensionBadge-remoteForeground", "#ffffff"],
  ["--vscode-extensionButton-background", "#e0e0e0"],
  ["--vscode-extensionButton-foreground", "#616161"],
  ["--vscode-extensionButton-hoverBackground", "#ffffff"],
  ["--vscode-extensionButton-prominentBackground", "#705697"],
  ["--vscode-extensionButton-prominentForeground", "#ffffff"],
  ["--vscode-extensionButton-prominentHoverBackground", "#5a4579"],
  ["--vscode-extensionButton-separator", "rgba(255, 255, 255, 0.4)"],
  ["--vscode-extensionIcon-preReleaseForeground", "#1d9271"],
  ["--vscode-extensionIcon-privateForeground", "rgba(0, 0, 0, 0.38)"],
  ["--vscode-extensionIcon-sponsorForeground", "#b51e78"],
  ["--vscode-extensionIcon-starForeground", "#df6100"],
  ["--vscode-extensionIcon-verifiedForeground", "#006ab1"],
  ["--vscode-focusBorder", "#9769dc"],
  ["--vscode-font-size", "13px"],
  ["--vscode-font-weight", "normal"],
  ["--vscode-foreground", "#616161"],
  ["--vscode-gauge-background", "rgba(78, 193, 229, 0.3)"],
  ["--vscode-gauge-errorBackground", "rgba(241, 137, 127, 0.3)"],
  ["--vscode-gauge-errorForeground", "#f1897f"],
  ["--vscode-gauge-foreground", "#4ec1e5"],
  ["--vscode-gauge-warningBackground", "rgba(255, 224, 85, 0.3)"],
  ["--vscode-gauge-warningForeground", "#ffe055"],
  ["--vscode-icon-foreground", "#424242"],
  ["--vscode-inlineChat-background", "#f3f3f3"],
  ["--vscode-inlineChat-border", "#c8c8c8"],
  ["--vscode-inlineChat-foreground", "#616161"],
  ["--vscode-inlineChat-shadow", "rgba(0, 0, 0, 0.16)"],
  ["--vscode-inlineChatDiff-inserted", "rgba(156, 204, 44, 0.13)"],
  ["--vscode-inlineChatDiff-removed", "rgba(255, 0, 0, 0.1)"],
  ["--vscode-inlineChatInput-background", "#ffffff"],
  ["--vscode-inlineChatInput-border", "#c8c8c8"],
  ["--vscode-inlineChatInput-focusBorder", "#9769dc"],
  ["--vscode-inlineChatInput-placeholderForeground", "rgba(97, 97, 97, 0.5)"],
  ["--vscode-inlineEdit-gutterIndicator\.background", "rgba(95, 95, 95, 0.09)"],
  ["--vscode-inlineEdit-gutterIndicator\.primaryBackground", "rgba(112, 86, 151, 0.5)"],
  ["--vscode-inlineEdit-gutterIndicator\.primaryBorder", "#705697"],
  ["--vscode-inlineEdit-gutterIndicator\.primaryForeground", "#ffffff"],
  ["--vscode-inlineEdit-gutterIndicator\.secondaryBackground", "#f3f3f3"],
  ["--vscode-inlineEdit-gutterIndicator\.secondaryBorder", "#c8c8c8"],
  ["--vscode-inlineEdit-gutterIndicator\.secondaryForeground", "#616161"],
  ["--vscode-inlineEdit-gutterIndicator\.successfulBackground", "#705697"],
  ["--vscode-inlineEdit-gutterIndicator\.successfulBorder", "#705697"],
  ["--vscode-inlineEdit-gutterIndicator\.successfulForeground", "#ffffff"],
  ["--vscode-inlineEdit-modifiedBackground", "rgba(156, 204, 44, 0.07)"],
  ["--vscode-inlineEdit-modifiedBorder", "rgba(62, 81, 18, 0.25)"],
  ["--vscode-inlineEdit-modifiedChangedLineBackground", "rgba(155, 185, 85, 0.14)"],
  ["--vscode-inlineEdit-modifiedChangedTextBackground", "rgba(156, 204, 44, 0.18)"],
  ["--vscode-inlineEdit-originalBackground", "rgba(255, 0, 0, 0.04)"],
  ["--vscode-inlineEdit-originalBorder", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-inlineEdit-originalChangedLineBackground", "rgba(255, 0, 0, 0.16)"],
  ["--vscode-inlineEdit-originalChangedTextBackground", "rgba(255, 0, 0, 0.16)"],
  ["--vscode-inlineEdit-tabWillAcceptModifiedBorder", "rgba(62, 81, 18, 0.25)"],
  ["--vscode-inlineEdit-tabWillAcceptOriginalBorder", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-input-background", "#ffffff"],
  ["--vscode-input-foreground", "#616161"],
  ["--vscode-input-placeholderForeground", "rgba(97, 97, 97, 0.5)"],
  ["--vscode-inputOption-activeBackground", "rgba(151, 105, 220, 0.2)"],
  ["--vscode-inputOption-activeBorder", "#adafb7"],
  ["--vscode-inputOption-activeForeground", "#000000"],
  ["--vscode-inputOption-hoverBackground", "rgba(184, 184, 184, 0.31)"],
  ["--vscode-inputValidation-errorBackground", "#ffeaea"],
  ["--vscode-inputValidation-errorBorder", "#f1897f"],
  ["--vscode-inputValidation-infoBackground", "#f2fcff"],
  ["--vscode-inputValidation-infoBorder", "#4ec1e5"],
  ["--vscode-inputValidation-warningBackground", "#fffee2"],
  ["--vscode-inputValidation-warningBorder", "#ffe055"],
  ["--vscode-interactive-activeCodeBorder", "#705697"],
  ["--vscode-interactive-inactiveCodeBorder", "#d3dbcd"],
  ["--vscode-keybindingLabel-background", "rgba(221, 221, 221, 0.4)"],
  ["--vscode-keybindingLabel-border", "rgba(204, 204, 204, 0.4)"],
  ["--vscode-keybindingLabel-bottomBorder", "rgba(187, 187, 187, 0.4)"],
  ["--vscode-keybindingLabel-foreground", "#555555"],
  ["--vscode-keybindingTable-headerBackground", "rgba(97, 97, 97, 0.04)"],
  ["--vscode-keybindingTable-rowsBackground", "rgba(97, 97, 97, 0.04)"],
  ["--vscode-list-activeSelectionBackground", "#c4d9b1"],
  ["--vscode-list-activeSelectionForeground", "#6c6c6c"],
  ["--vscode-list-deemphasizedForeground", "#8e8e90"],
  ["--vscode-list-dropBackground", "#d6ebff"],
  ["--vscode-list-dropBetweenBackground", "#424242"],
  ["--vscode-list-errorForeground", "#b01011"],
  ["--vscode-list-filterMatchBackground", "rgba(237, 201, 216, 0.6)"],
  ["--vscode-list-focusHighlightForeground", "#9769dc"],
  ["--vscode-list-focusOutline", "#9769dc"],
  ["--vscode-list-highlightForeground", "#9769dc"],
  ["--vscode-list-hoverBackground", "#e0e0e0"],
  ["--vscode-list-inactiveSelectionBackground", "#d3dbcd"],
  ["--vscode-list-invalidItemForeground", "#b89500"],
  ["--vscode-list-warningForeground", "#855f00"],
  ["--vscode-listFilterWidget-background", "#f3f3f3"],
  ["--vscode-listFilterWidget-noMatchesOutline", "#be1100"],
  ["--vscode-listFilterWidget-outline", "rgba(0, 0, 0, 0)"],
  ["--vscode-listFilterWidget-shadow", "rgba(0, 0, 0, 0.16)"],
  ["--vscode-markdownAlert-caution\.foreground", "#e51400"],
  ["--vscode-markdownAlert-important\.foreground", "#652d90"],
  ["--vscode-markdownAlert-note\.foreground", "#0063d3"],
  ["--vscode-markdownAlert-tip\.foreground", "#388a34"],
  ["--vscode-markdownAlert-warning\.foreground", "#bf8803"],
  ["--vscode-mcpIcon-starForeground", "#df6100"],
  ["--vscode-menu-background", "#f5f5f5"],
  ["--vscode-menu-foreground", "#616161"],
  ["--vscode-menu-selectionBackground", "#c4d9b1"],
  ["--vscode-menu-selectionForeground", "#6c6c6c"],
  ["--vscode-menu-separatorBackground", "#d4d4d4"],
  ["--vscode-menubar-selectionBackground", "rgba(184, 184, 184, 0.31)"],
  ["--vscode-menubar-selectionForeground", "#333333"],
  ["--vscode-merge-commonContentBackground", "rgba(96, 96, 96, 0.16)"],
  ["--vscode-merge-commonHeaderBackground", "rgba(96, 96, 96, 0.4)"],
  ["--vscode-merge-currentContentBackground", "rgba(64, 200, 174, 0.2)"],
  ["--vscode-merge-currentHeaderBackground", "rgba(64, 200, 174, 0.5)"],
  ["--vscode-merge-incomingContentBackground", "rgba(64, 166, 255, 0.2)"],
  ["--vscode-merge-incomingHeaderBackground", "rgba(64, 166, 255, 0.5)"],
  ["--vscode-mergeEditor-change\.background", "rgba(155, 185, 85, 0.2)"],
  ["--vscode-mergeEditor-change\.word\.background", "rgba(156, 204, 44, 0.4)"],
  ["--vscode-mergeEditor-changeBase\.background", "#ffcccc"],
  ["--vscode-mergeEditor-changeBase\.word\.background", "#ffa3a3"],
  ["--vscode-mergeEditor-conflict\.handled\.minimapOverViewRuler", "rgba(173, 172, 168, 0.93)"],
  ["--vscode-mergeEditor-conflict\.handledFocused\.border", "rgba(193, 193, 193, 0.8)"],
  ["--vscode-mergeEditor-conflict\.handledUnfocused\.border", "rgba(134, 134, 134, 0.29)"],
  ["--vscode-mergeEditor-conflict\.input1\.background", "rgba(64, 200, 174, 0.2)"],
  ["--vscode-mergeEditor-conflict\.input2\.background", "rgba(64, 166, 255, 0.2)"],
  ["--vscode-mergeEditor-conflict\.unhandled\.minimapOverViewRuler", "#fcba03"],
  ["--vscode-mergeEditor-conflict\.unhandledFocused\.border", "#ffa600"],
  ["--vscode-mergeEditor-conflict\.unhandledUnfocused\.border", "#ffa600"],
  ["--vscode-mergeEditor-conflictingLines\.background", "rgba(255, 234, 0, 0.28)"],
  ["--vscode-minimap-chatEditHighlight", "rgba(245, 245, 245, 0.6)"],
  ["--vscode-minimap-errorHighlight", "rgba(255, 18, 18, 0.7)"],
  ["--vscode-minimap-findMatchHighlight", "rgba(237, 201, 216, 0.6)"],
  ["--vscode-minimap-foregroundOpacity", "#000000"],
  ["--vscode-minimap-infoHighlight", "#0063d3"],
  ["--vscode-minimap-selectionHighlight", "#c9d0d9"],
  ["--vscode-minimap-selectionOccurrenceHighlight", "rgba(224, 228, 234, 0.6)"],
  ["--vscode-minimap-warningHighlight", "#bf8803"],
  ["--vscode-minimapGutter-addedBackground", "#48985d"],
  ["--vscode-minimapGutter-deletedBackground", "#e51400"],
  ["--vscode-minimapGutter-modifiedBackground", "#2090d3"],
  ["--vscode-minimapSlider-activeBackground", "rgba(0, 0, 0, 0.3)"],
  ["--vscode-minimapSlider-background", "rgba(100, 100, 100, 0.2)"],
  ["--vscode-minimapSlider-hoverBackground", "rgba(100, 100, 100, 0.35)"],
  ["--vscode-multiDiffEditor-background", "#f5f5f5"],
  ["--vscode-multiDiffEditor-border", "#cccccc"],
  ["--vscode-multiDiffEditor-headerBackground", "#ececec"],
  ["--vscode-notebook-cellBorderColor", "#d3dbcd"],
  ["--vscode-notebook-cellEditorBackground", "#f2f2f2"],
  ["--vscode-notebook-cellInsertionIndicator", "#9769dc"],
  ["--vscode-notebook-cellStatusBarItemHoverBackground", "rgba(0, 0, 0, 0.08)"],
  ["--vscode-notebook-cellToolbarSeparator", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-notebook-editorBackground", "#f5f5f5"],
  ["--vscode-notebook-focusedCellBorder", "#9769dc"],
  ["--vscode-notebook-focusedEditorBorder", "#9769dc"],
  ["--vscode-notebook-inactiveFocusedCellBorder", "#d3dbcd"],
  ["--vscode-notebook-selectedCellBackground", "#d3dbcd"],
  ["--vscode-notebook-selectedCellBorder", "#d3dbcd"],
  ["--vscode-notebook-symbolHighlightBackground", "rgba(253, 255, 0, 0.2)"],
  ["--vscode-notebookEditorOverviewRuler-runningCellForeground", "#388a34"],
  ["--vscode-notebookScrollbarSlider-activeBackground", "rgba(0, 0, 0, 0.6)"],
  ["--vscode-notebookScrollbarSlider-background", "rgba(100, 100, 100, 0.4)"],
  ["--vscode-notebookScrollbarSlider-hoverBackground", "rgba(100, 100, 100, 0.7)"],
  ["--vscode-notebookStatusErrorIcon-foreground", "#f1897f"],
  ["--vscode-notebookStatusRunningIcon-foreground", "#616161"],
  ["--vscode-notebookStatusSuccessIcon-foreground", "#388a34"],
  ["--vscode-notificationCenterHeader-background", "#e7e7e7"],
  ["--vscode-notificationLink-foreground", "#006ab1"],
  ["--vscode-notifications-background", "#f3f3f3"],
  ["--vscode-notifications-border", "#e7e7e7"],
  ["--vscode-notifications-foreground", "#616161"],
  ["--vscode-notificationsErrorIcon-foreground", "#e51400"],
  ["--vscode-notificationsInfoIcon-foreground", "#0063d3"],
  ["--vscode-notificationsWarningIcon-foreground", "#bf8803"],
  ["--vscode-panel-background", "#f5f5f5"],
  ["--vscode-panel-border", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-panel-dropBorder", "#424242"],
  ["--vscode-panelInput-border", "#dddddd"],
  ["--vscode-panelSection-border", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-panelSection-dropBackground", "rgba(201, 208, 217, 0.53)"],
  ["--vscode-panelSectionHeader-background", "rgba(128, 128, 128, 0.2)"],
  ["--vscode-panelStickyScroll-background", "#f5f5f5"],
  ["--vscode-panelStickyScroll-shadow", "#dddddd"],
  ["--vscode-panelTitle-activeBorder", "#424242"],
  ["--vscode-panelTitle-activeForeground", "#424242"],
  ["--vscode-panelTitle-inactiveForeground", "rgba(66, 66, 66, 0.75)"],
  ["--vscode-panelTitleBadge-background", "#705697"],
  ["--vscode-panelTitleBadge-foreground", "#ffffff"],
  ["--vscode-peekView-border", "#705697"],
  ["--vscode-peekViewEditor-background", "#f2f8fc"],
  ["--vscode-peekViewEditor-matchHighlightBackground", "#c2dfe3"],
  ["--vscode-peekViewEditorGutter-background", "#f2f8fc"],
  ["--vscode-peekViewEditorStickyScroll-background", "#f2f8fc"],
  ["--vscode-peekViewEditorStickyScrollGutter-background", "#f2f8fc"],
  ["--vscode-peekViewResult-background", "#f2f8fc"],
  ["--vscode-peekViewResult-fileForeground", "#1e1e1e"],
  ["--vscode-peekViewResult-lineForeground", "#646465"],
  ["--vscode-peekViewResult-matchHighlightBackground", "#93c6d6"],
  ["--vscode-peekViewResult-selectionBackground", "rgba(51, 153, 255, 0.2)"],
  ["--vscode-peekViewResult-selectionForeground", "#6c6c6c"],
  ["--vscode-peekViewTitle-background", "#f2f8fc"],
  ["--vscode-peekViewTitleDescription-foreground", "#616161"],
  ["--vscode-peekViewTitleLabel-foreground", "#000000"],
  ["--vscode-pickerGroup-border", "#749351"],
  ["--vscode-pickerGroup-foreground", "#a6b39b"],
  ["--vscode-ports-iconRunningProcessForeground", "#749351"],
  ["--vscode-problemsErrorIcon-foreground", "#e51400"],
  ["--vscode-problemsInfoIcon-foreground", "#0063d3"],
  ["--vscode-problemsWarningIcon-foreground", "#bf8803"],
  ["--vscode-profileBadge-background", "#c4c4c4"],
  ["--vscode-profileBadge-foreground", "#333333"],
  ["--vscode-profiles-sashBorder", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-progressBar-background", "#705697"],
  ["--vscode-quickInput-background", "#f3f3f3"],
  ["--vscode-quickInput-foreground", "#616161"],
  ["--vscode-quickInputList-focusBackground", "#cadeb9"],
  ["--vscode-quickInputList-focusForeground", "#6c6c6c"],
  ["--vscode-quickInputTitle-background", "rgba(0, 0, 0, 0.06)"],
  ["--vscode-radio-activeBackground", "rgba(151, 105, 220, 0.2)"],
  ["--vscode-radio-activeBorder", "#adafb7"],
  ["--vscode-radio-activeForeground", "#000000"],
  ["--vscode-radio-inactiveBorder", "rgba(0, 0, 0, 0.2)"],
  ["--vscode-radio-inactiveHoverBackground", "rgba(184, 184, 184, 0.31)"],
  ["--vscode-remoteHub-decorations\.addedForegroundColor", "#587c0c"],
  ["--vscode-remoteHub-decorations\.conflictForegroundColor", "#ad0707"],
  ["--vscode-remoteHub-decorations\.deletedForegroundColor", "#ad0707"],
  ["--vscode-remoteHub-decorations\.ignoredResourceForeground", "#8e8e90"],
  ["--vscode-remoteHub-decorations\.incomingAddedForegroundColor", "#587c0c"],
  ["--vscode-remoteHub-decorations\.incomingDeletedForegroundColor", "#ad0707"],
  ["--vscode-remoteHub-decorations\.incomingModifiedForegroundColor", "#895503"],
  ["--vscode-remoteHub-decorations\.incomingRenamedForegroundColor", "#007100"],
  ["--vscode-remoteHub-decorations\.modifiedForegroundColor", "#895503"],
  ["--vscode-remoteHub-decorations\.possibleConflictForegroundColor", "#855f00"],
  ["--vscode-remoteHub-decorations\.submoduleForegroundColor", "#1258a7"],
  ["--vscode-remoteHub-decorations\.workspaceRepositoriesView\.hasUncommittedChangesForegroundColor", "#895503"],
  ["--vscode-sash-hoverBorder", "#9769dc"],
  ["--vscode-scmGraph-foreground1", "#ffb000"],
  ["--vscode-scmGraph-foreground2", "#dc267f"],
  ["--vscode-scmGraph-foreground3", "#994f00"],
  ["--vscode-scmGraph-foreground4", "#40b0a6"],
  ["--vscode-scmGraph-foreground5", "#b66dff"],
  ["--vscode-scmGraph-historyItemBaseRefColor", "#ea5c00"],
  ["--vscode-scmGraph-historyItemHoverAdditionsForeground", "#587c0c"],
  ["--vscode-scmGraph-historyItemHoverDefaultLabelBackground", "rgba(112, 86, 151, 0.67)"],
  ["--vscode-scmGraph-historyItemHoverDefaultLabelForeground", "#616161"],
  ["--vscode-scmGraph-historyItemHoverDeletionsForeground", "#ad0707"],
  ["--vscode-scmGraph-historyItemHoverLabelForeground", "#f5f5f5"],
  ["--vscode-scmGraph-historyItemRefColor", "#0063d3"],
  ["--vscode-scmGraph-historyItemRemoteRefColor", "#652d90"],
  ["--vscode-scrollbar-shadow", "#dddddd"],
  ["--vscode-scrollbarSlider-activeBackground", "rgba(0, 0, 0, 0.6)"],
  ["--vscode-scrollbarSlider-background", "rgba(100, 100, 100, 0.4)"],
  ["--vscode-scrollbarSlider-hoverBackground", "rgba(100, 100, 100, 0.7)"],
  ["--vscode-search-resultsInfoForeground", "#616161"],
  ["--vscode-searchEditor-findMatchBackground", "rgba(237, 201, 216, 0.4)"],
  ["--vscode-selection-background", "#c9d0d9"],
  ["--vscode-settings-checkboxBackground", "#f5f5f5"],
  ["--vscode-settings-checkboxBorder", "#cecece"],
  ["--vscode-settings-checkboxForeground", "#616161"],
  ["--vscode-settings-dropdownBackground", "#f5f5f5"],
  ["--vscode-settings-dropdownBorder", "#cecece"],
  ["--vscode-settings-dropdownForeground", "#616161"],
  ["--vscode-settings-dropdownListBorder", "#c8c8c8"],
  ["--vscode-settings-focusedRowBackground", "rgba(224, 224, 224, 0.6)"],
  ["--vscode-settings-focusedRowBorder", "#9769dc"],
  ["--vscode-settings-headerBorder", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-settings-headerForeground", "#444444"],
  ["--vscode-settings-modifiedItemIndicator", "#66afe0"],
  ["--vscode-settings-numberInputBackground", "#ffffff"],
  ["--vscode-settings-numberInputForeground", "#616161"],
  ["--vscode-settings-rowHoverBackground", "rgba(224, 224, 224, 0.3)"],
  ["--vscode-settings-sashBorder", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-settings-settingsHeaderHoverForeground", "rgba(68, 68, 68, 0.7)"],
  ["--vscode-settings-textInputBackground", "#ffffff"],
  ["--vscode-settings-textInputForeground", "#616161"],
  ["--vscode-sideBar-background", "#f2f2f2"],
  ["--vscode-sideBar-dropBackground", "rgba(201, 208, 217, 0.53)"],
  ["--vscode-sideBarSectionHeader-background", "#ede8ef"],
  ["--vscode-sideBarStickyScroll-background", "#f2f2f2"],
  ["--vscode-sideBarStickyScroll-shadow", "#dddddd"],
  ["--vscode-sideBarTitle-background", "#f2f2f2"],
  ["--vscode-sideBySideEditor-horizontalBorder", "#e7e7e7"],
  ["--vscode-sideBySideEditor-verticalBorder", "#e7e7e7"],
  ["--vscode-simpleFindWidget-sashBorder", "#c8c8c8"],
  ["--vscode-statusBar-background", "#705697"],
  ["--vscode-statusBar-debuggingBackground", "#705697"],
  ["--vscode-statusBar-debuggingForeground", "#ffffff"],
  ["--vscode-statusBar-focusBorder", "#ffffff"],
  ["--vscode-statusBar-foreground", "#ffffff"],
  ["--vscode-statusBar-noFolderBackground", "#705697"],
  ["--vscode-statusBar-noFolderForeground", "#ffffff"],
  ["--vscode-statusBarItem-activeBackground", "rgba(255, 255, 255, 0.18)"],
  ["--vscode-statusBarItem-compactHoverBackground", "rgba(0, 0, 0, 0.12)"],
  ["--vscode-statusBarItem-errorBackground", "#c72516"],
  ["--vscode-statusBarItem-errorForeground", "#ffffff"],
  ["--vscode-statusBarItem-errorHoverBackground", "rgba(0, 0, 0, 0.12)"],
  ["--vscode-statusBarItem-errorHoverForeground", "#ffffff"],
  ["--vscode-statusBarItem-focusBorder", "#ffffff"],
  ["--vscode-statusBarItem-hoverBackground", "rgba(0, 0, 0, 0.12)"],
  ["--vscode-statusBarItem-hoverForeground", "#ffffff"],
  ["--vscode-statusBarItem-offlineBackground", "#6c1717"],
  ["--vscode-statusBarItem-offlineForeground", "#ffffff"],
  ["--vscode-statusBarItem-offlineHoverBackground", "rgba(0, 0, 0, 0.12)"],
  ["--vscode-statusBarItem-offlineHoverForeground", "#ffffff"],
  ["--vscode-statusBarItem-prominentBackground", "rgba(0, 0, 0, 0.5)"],
  ["--vscode-statusBarItem-prominentForeground", "#ffffff"],
  ["--vscode-statusBarItem-prominentHoverBackground", "rgba(0, 0, 0, 0.12)"],
  ["--vscode-statusBarItem-prominentHoverForeground", "#ffffff"],
  ["--vscode-statusBarItem-remoteBackground", "#4e3c69"],
  ["--vscode-statusBarItem-remoteForeground", "#ffffff"],
  ["--vscode-statusBarItem-remoteHoverBackground", "rgba(0, 0, 0, 0.12)"],
  ["--vscode-statusBarItem-remoteHoverForeground", "#ffffff"],
  ["--vscode-statusBarItem-warningBackground", "#725102"],
  ["--vscode-statusBarItem-warningForeground", "#ffffff"],
  ["--vscode-statusBarItem-warningHoverBackground", "rgba(0, 0, 0, 0.12)"],
  ["--vscode-statusBarItem-warningHoverForeground", "#ffffff"],
  ["--vscode-strokeThickness", "1px"],
  ["--vscode-symbolIcon-arrayForeground", "#616161"],
  ["--vscode-symbolIcon-booleanForeground", "#616161"],
  ["--vscode-symbolIcon-classForeground", "#d67e00"],
  ["--vscode-symbolIcon-colorForeground", "#616161"],
  ["--vscode-symbolIcon-constantForeground", "#616161"],
  ["--vscode-symbolIcon-constructorForeground", "#652d90"],
  ["--vscode-symbolIcon-enumeratorForeground", "#d67e00"],
  ["--vscode-symbolIcon-enumeratorMemberForeground", "#007acc"],
  ["--vscode-symbolIcon-eventForeground", "#d67e00"],
  ["--vscode-symbolIcon-fieldForeground", "#007acc"],
  ["--vscode-symbolIcon-fileForeground", "#616161"],
  ["--vscode-symbolIcon-folderForeground", "#616161"],
  ["--vscode-symbolIcon-functionForeground", "#652d90"],
  ["--vscode-symbolIcon-interfaceForeground", "#007acc"],
  ["--vscode-symbolIcon-keyForeground", "#616161"],
  ["--vscode-symbolIcon-keywordForeground", "#616161"],
  ["--vscode-symbolIcon-methodForeground", "#652d90"],
  ["--vscode-symbolIcon-moduleForeground", "#616161"],
  ["--vscode-symbolIcon-namespaceForeground", "#616161"],
  ["--vscode-symbolIcon-nullForeground", "#616161"],
  ["--vscode-symbolIcon-numberForeground", "#616161"],
  ["--vscode-symbolIcon-objectForeground", "#616161"],
  ["--vscode-symbolIcon-operatorForeground", "#616161"],
  ["--vscode-symbolIcon-packageForeground", "#616161"],
  ["--vscode-symbolIcon-propertyForeground", "#616161"],
  ["--vscode-symbolIcon-referenceForeground", "#616161"],
  ["--vscode-symbolIcon-snippetForeground", "#616161"],
  ["--vscode-symbolIcon-stringForeground", "#616161"],
  ["--vscode-symbolIcon-structForeground", "#616161"],
  ["--vscode-symbolIcon-textForeground", "#616161"],
  ["--vscode-symbolIcon-typeParameterForeground", "#616161"],
  ["--vscode-symbolIcon-unitForeground", "#616161"],
  ["--vscode-symbolIcon-variableForeground", "#007acc"],
  ["--vscode-tab-activeBackground", "#f5f5f5"],
  ["--vscode-tab-activeForeground", "#333333"],
  ["--vscode-tab-activeModifiedBorder", "#33aaee"],
  ["--vscode-tab-border", "#f3f3f3"],
  ["--vscode-tab-dragAndDropBorder", "#333333"],
  ["--vscode-tab-inactiveBackground", "#ececec"],
  ["--vscode-tab-inactiveForeground", "rgba(51, 51, 51, 0.7)"],
  ["--vscode-tab-inactiveModifiedBorder", "rgba(51, 170, 238, 0.5)"],
  ["--vscode-tab-lastPinnedBorder", "#c9d0d9"],
  ["--vscode-tab-selectedBackground", "#f5f5f5"],
  ["--vscode-tab-selectedForeground", "#333333"],
  ["--vscode-tab-unfocusedActiveBackground", "#f5f5f5"],
  ["--vscode-tab-unfocusedActiveForeground", "rgba(51, 51, 51, 0.7)"],
  ["--vscode-tab-unfocusedActiveModifiedBorder", "rgba(51, 170, 238, 0.7)"],
  ["--vscode-tab-unfocusedInactiveBackground", "#ececec"],
  ["--vscode-tab-unfocusedInactiveForeground", "rgba(51, 51, 51, 0.35)"],
  ["--vscode-tab-unfocusedInactiveModifiedBorder", "rgba(51, 170, 238, 0.25)"],
  ["--vscode-terminal-ansiBlack", "#000000"],
  ["--vscode-terminal-ansiBlue", "#0451a5"],
  ["--vscode-terminal-ansiBrightBlack", "#666666"],
  ["--vscode-terminal-ansiBrightBlue", "#0451a5"],
  ["--vscode-terminal-ansiBrightCyan", "#0598bc"],
  ["--vscode-terminal-ansiBrightGreen", "#14ce14"],
  ["--vscode-terminal-ansiBrightMagenta", "#bc05bc"],
  ["--vscode-terminal-ansiBrightRed", "#cd3131"],
  ["--vscode-terminal-ansiBrightWhite", "#a5a5a5"],
  ["--vscode-terminal-ansiBrightYellow", "#b5ba00"],
  ["--vscode-terminal-ansiCyan", "#0598bc"],
  ["--vscode-terminal-ansiGreen", "#107c10"],
  ["--vscode-terminal-ansiMagenta", "#bc05bc"],
  ["--vscode-terminal-ansiRed", "#cd3131"],
  ["--vscode-terminal-ansiWhite", "#555555"],
  ["--vscode-terminal-ansiYellow", "#949800"],
  ["--vscode-terminal-border", "rgba(128, 128, 128, 0.35)"],
  ["--vscode-terminal-dropBackground", "rgba(201, 208, 217, 0.53)"],
  ["--vscode-terminal-findMatchBackground", "#bf9cac"],
  ["--vscode-terminal-findMatchHighlightBackground", "rgba(237, 201, 216, 0.6)"],
  ["--vscode-terminal-foreground", "#333333"],
  ["--vscode-terminal-hoverHighlightBackground", "rgba(173, 214, 255, 0.07)"],
  ["--vscode-terminal-inactiveSelectionBackground", "rgba(201, 208, 217, 0.5)"],
  ["--vscode-terminal-initialHintForeground", "rgba(0, 0, 0, 0.47)"],
  ["--vscode-terminal-selectionBackground", "#c9d0d9"],
  ["--vscode-terminalCommandDecoration-defaultBackground", "rgba(0, 0, 0, 0.25)"],
  ["--vscode-terminalCommandDecoration-errorBackground", "#e51400"],
  ["--vscode-terminalCommandDecoration-successBackground", "#2090d3"],
  ["--vscode-terminalCommandGuide-foreground", "#d3dbcd"],
  ["--vscode-terminalOverviewRuler-border", "rgba(127, 127, 127, 0.3)"],
  ["--vscode-terminalOverviewRuler-cursorForeground", "rgba(160, 160, 160, 0.8)"],
  ["--vscode-terminalOverviewRuler-findMatchForeground", "rgba(209, 134, 22, 0.49)"],
  ["--vscode-terminalStickyScrollHover-background", "#f0f0f0"],
  ["--vscode-terminalSymbolIcon-aliasForeground", "#652d90"],
  ["--vscode-terminalSymbolIcon-argumentForeground", "#007acc"],
  ["--vscode-terminalSymbolIcon-branchForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-commitForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-fileForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-flagForeground", "#d67e00"],
  ["--vscode-terminalSymbolIcon-folderForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-methodForeground", "#652d90"],
  ["--vscode-terminalSymbolIcon-optionForeground", "#d67e00"],
  ["--vscode-terminalSymbolIcon-optionValueForeground", "#007acc"],
  ["--vscode-terminalSymbolIcon-pullRequestDoneForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-pullRequestForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-remoteForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-stashForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-symbolicLinkFileForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-symbolicLinkFolderForeground", "#616161"],
  ["--vscode-terminalSymbolIcon-symbolText", "#616161"],
  ["--vscode-terminalSymbolIcon-tagForeground", "#616161"],
  ["--vscode-testing-coverCountBadgeBackground", "rgba(112, 86, 151, 0.67)"],
  ["--vscode-testing-coverCountBadgeForeground", "#333333"],
  ["--vscode-testing-coveredBackground", "rgba(156, 204, 44, 0.25)"],
  ["--vscode-testing-coveredBorder", "rgba(156, 204, 44, 0.19)"],
  ["--vscode-testing-coveredGutterBackground", "rgba(156, 204, 44, 0.15)"],
  ["--vscode-testing-iconErrored", "#f14c4c"],
  ["--vscode-testing-iconErrored\.retired", "rgba(241, 76, 76, 0.7)"],
  ["--vscode-testing-iconFailed", "#f14c4c"],
  ["--vscode-testing-iconFailed\.retired", "rgba(241, 76, 76, 0.7)"],
  ["--vscode-testing-iconPassed", "#73c991"],
  ["--vscode-testing-iconPassed\.retired", "rgba(115, 201, 145, 0.7)"],
  ["--vscode-testing-iconQueued", "#cca700"],
  ["--vscode-testing-iconQueued\.retired", "rgba(204, 167, 0, 0.7)"],
  ["--vscode-testing-iconSkipped", "#848484"],
  ["--vscode-testing-iconSkipped\.retired", "rgba(132, 132, 132, 0.7)"],
  ["--vscode-testing-iconUnset", "#848484"],
  ["--vscode-testing-iconUnset\.retired", "rgba(132, 132, 132, 0.7)"],
  ["--vscode-testing-message\.error\.badgeBackground", "#e51400"],
  ["--vscode-testing-message\.error\.badgeBorder", "#e51400"],
  ["--vscode-testing-message\.error\.badgeForeground", "#ffffff"],
  ["--vscode-testing-message\.info\.decorationForeground", "rgba(51, 51, 51, 0.5)"],
  ["--vscode-testing-messagePeekBorder", "#0063d3"],
  ["--vscode-testing-messagePeekHeaderBackground", "rgba(0, 99, 211, 0.1)"],
  ["--vscode-testing-peekBorder", "#e51400"],
  ["--vscode-testing-peekHeaderBackground", "rgba(229, 20, 0, 0.1)"],
  ["--vscode-testing-runAction", "#73c991"],
  ["--vscode-testing-uncoveredBackground", "rgba(255, 0, 0, 0.2)"],
  ["--vscode-testing-uncoveredBorder", "rgba(255, 0, 0, 0.15)"],
  ["--vscode-testing-uncoveredBranchBackground", "#f99393"],
  ["--vscode-testing-uncoveredGutterBackground", "rgba(255, 0, 0, 0.3)"],
  ["--vscode-textBlockQuote-background", "#f2f2f2"],
  ["--vscode-textBlockQuote-border", "rgba(0, 122, 204, 0.5)"],
  ["--vscode-textCodeBlock-background", "rgba(220, 220, 220, 0.4)"],
  ["--vscode-textLink-activeForeground", "#006ab1"],
  ["--vscode-textLink-foreground", "#006ab1"],
  ["--vscode-textPreformat-background", "rgba(0, 0, 0, 0.1)"],
  ["--vscode-textPreformat-foreground", "#a31515"],
  ["--vscode-textSeparator-foreground", "rgba(0, 0, 0, 0.18)"],
  ["--vscode-titleBar-activeBackground", "#c4b7d7"],
  ["--vscode-titleBar-activeForeground", "#333333"],
  ["--vscode-titleBar-inactiveBackground", "rgba(196, 183, 215, 0.6)"],
  ["--vscode-titleBar-inactiveForeground", "rgba(51, 51, 51, 0.6)"],
  ["--vscode-toolbar-activeBackground", "rgba(166, 166, 166, 0.31)"],
  ["--vscode-toolbar-hoverBackground", "rgba(184, 184, 184, 0.31)"],
  ["--vscode-tree-inactiveIndentGuidesStroke", "rgba(169, 169, 169, 0.4)"],
  ["--vscode-tree-indentGuidesStroke", "#a9a9a9"],
  ["--vscode-tree-tableColumnsBorder", "rgba(97, 97, 97, 0.13)"],
  ["--vscode-tree-tableOddRowsBackground", "rgba(97, 97, 97, 0.04)"],
  ["--vscode-walkThrough-embeddedEditorBackground", "rgba(0, 0, 0, 0.08)"],
  ["--vscode-walkthrough-stepTitle\.foreground", "#000000"],
  ["--vscode-welcomePage-progress\.background", "#ffffff"],
  ["--vscode-welcomePage-progress\.foreground", "#006ab1"],
  ["--vscode-welcomePage-tileBackground", "#f0f0f7"],
  ["--vscode-welcomePage-tileBorder", "rgba(0, 0, 0, 0.1)"],
  ["--vscode-welcomePage-tileHoverBackground", "#dbdbdb"],
  ["--vscode-widget-shadow", "rgba(0, 0, 0, 0.16)"],
];
