"use strict";

/**
 * Runs inside the VS Code extension host, launched by ./sync.mjs. Cycles
 * through the built-in themes, opens a webview per theme, and dumps the
 * injected --vscode-* variables and the "_defaultStyles" stylesheet to
 * THEME_SYNC_OUTPUT_DIR.
 */

const fs = require("node:fs");
const path = require("node:path");
const vscode = require("vscode");

/** Provenance name stamped into generated file headers. */
const SCRIPT_NAME = "pnpm sync:vscode-themes";

/**
 * Output slug and built-in theme name.
 * @type {ReadonlyArray<readonly [string, string]>}
 */
const THEMES = [
	["dark", "Default Dark Modern"],
	["light", "Default Light Modern"],
	["high-contrast", "Default High Contrast"],
	["high-contrast-light", "Default High Contrast Light"],
];

/**
 * Dark is the startup default, so it is captured last: every capture must
 * follow a real theme-change event, because the startup theme's data may
 * still be partially loaded when the extension host starts.
 * @type {ReadonlyArray<readonly [string, string]>}
 */
const CAPTURE_ORDER = [...THEMES.slice(1), THEMES[0]];

const WEBVIEW_HTML = `<!DOCTYPE html>
<html>
<body>
<script>
	const vscodeApi = acquireVsCodeApi();
	function collect() {
		const style = document.documentElement.style;
		const variables = [];
		for (let i = 0; i < style.length; i++) {
			const name = style[i];
			if (name.startsWith("--vscode-")) {
				variables.push([name, style.getPropertyValue(name)]);
			}
		}
		const defaultStyles = document.getElementById("_defaultStyles");
		return {
			variables,
			defaultStyles: defaultStyles ? defaultStyles.textContent : null,
		};
	}
	// Variables usually precede content, but poll in case they arrive late.
	let attempts = 0;
	const timer = setInterval(() => {
		const data = collect();
		attempts++;
		if (data.variables.length > 0 || attempts >= 50) {
			clearInterval(timer);
			vscodeApi.postMessage(data);
		}
	}, 100);
</script>
</body>
</html>`;

/**
 * Activates a theme and resolves on the resulting theme-change event;
 * rejects if it does not activate within 10s.
 */
function setTheme(themeName) {
	return new Promise((resolvePromise, rejectPromise) => {
		const timer = setTimeout(() => {
			disposable.dispose();
			rejectPromise(new Error(`Theme "${themeName}" did not activate`));
		}, 10_000);
		const disposable = vscode.window.onDidChangeActiveColorTheme(() => {
			disposable.dispose();
			clearTimeout(timer);
			resolvePromise();
		});
		vscode.workspace
			.getConfiguration("workbench")
			.update("colorTheme", themeName, vscode.ConfigurationTarget.Global)
			.then(undefined, rejectPromise);
	});
}

/** Opens a webview and resolves with the payload collect() posts back. */
function dumpWebview() {
	return new Promise((resolvePromise, rejectPromise) => {
		const panel = vscode.window.createWebviewPanel(
			"themeSync",
			"Theme Sync",
			vscode.ViewColumn.One,
			{ enableScripts: true },
		);
		const timer = setTimeout(() => {
			panel.dispose();
			rejectPromise(new Error("Timed out waiting for webview message"));
		}, 30_000);
		panel.webview.onDidReceiveMessage((message) => {
			clearTimeout(timer);
			panel.dispose();
			resolvePromise(message);
		});
		panel.webview.html = WEBVIEW_HTML;
	});
}

/** Test entry point invoked by @vscode/test-electron. */
async function run() {
	const outputDir = process.env.THEME_SYNC_OUTPUT_DIR;
	if (!outputDir) {
		throw new Error("THEME_SYNC_OUTPUT_DIR is not set");
	}
	fs.mkdirSync(outputDir, { recursive: true });
	const captured = {};

	for (const [slug, themeName] of CAPTURE_ORDER) {
		await setTheme(themeName);
		const { variables, defaultStyles } = await dumpWebview();
		if (variables.length === 0) {
			throw new Error(`No --vscode-* variables captured for ${themeName}`);
		}
		variables.sort((a, b) => a[0].localeCompare(b[0]));
		captured[slug] = variables;
		console.log(`Captured ${variables.length} variables for ${themeName}`);

		if (slug === "dark") {
			if (!defaultStyles) {
				throw new Error(
					"Default webview stylesheet (_defaultStyles) not found",
				);
			}
			const header = `/* Generated by ${SCRIPT_NAME} from VS Code ${vscode.version}. Do not edit by hand. */\n`;
			fs.writeFileSync(
				path.join(outputDir, "default-styles.css"),
				header + defaultStyles.trim() + "\n",
			);
			console.log("Captured default webview stylesheet");
		}
	}

	// Keys in THEMES order so resyncs diff cleanly against the committed file.
	const themes = {};
	for (const [slug] of THEMES) {
		themes[slug] = captured[slug];
	}

	// Minified single line, excluded from Prettier, so resyncs produce a
	// one-line diff instead of thousands of formatted lines.
	fs.writeFileSync(
		path.join(outputDir, "themes.json"),
		JSON.stringify({
			$comment: `Generated by ${SCRIPT_NAME} from VS Code ${vscode.version}. Do not edit by hand.`,
			vscode: vscode.version,
			themes,
		}) + "\n",
	);
}

module.exports = { run };
