import react from "@vitejs/plugin-react";
import { resolve } from "node:path";
import { defineConfig, type UserConfig } from "vite";

/**
 * Create a Vite config for a webview package
 * @param webviewName - Name of the webview (used for output path)
 * @param dirname - __dirname of the calling config file
 */
export function createWebviewConfig(
	webviewName: string,
	dirname: string,
): UserConfig {
	const production = process.env.NODE_ENV === "production";

	return defineConfig({
		// Use relative URLs for assets (fonts, etc.) in CSS
		base: "./",
		plugins: [
			react({
				babel: {
					plugins: [["babel-plugin-react-compiler", {}]],
				},
			}),
		],
		build: {
			outDir: resolve(dirname, `../../dist/webviews/${webviewName}`),
			emptyOutDir: true,
			// Target modern browsers (VS Code webview uses Chromium from Electron)
			target: "esnext",
			// Skip gzip size calculation for faster builds
			reportCompressedSize: false,
			rollupOptions: {
				// HTML is generated by the extension with CSP headers
				input: resolve(dirname, "src/index.tsx"),
				output: {
					entryFileNames: "index.js",
					// Keep fonts with original names for proper CSS references
					assetFileNames: (assetInfo) => {
						if (assetInfo.names?.[0]?.endsWith(".ttf")) {
							return "codicon.ttf";
						}
						return "index.[ext]";
					},
				},
			},
			// Keeps extension size down; build locally to map stack traces
			sourcemap: !production,
		},
		resolve: {
			alias: {
				"@repo/webview-shared": resolve(dirname, "../webview-shared/src"),
			},
		},
	});
}
