import babel from "@rolldown/plugin-babel";
import react, { reactCompilerPreset } from "@vitejs/plugin-react";
import { resolve } from "node:path";
import { defineConfig, type Plugin, type UserConfig } from "vite";

/**
 * Create a base Vite config for a webview package (no framework).
 */
export function createBaseWebviewConfig(
	webviewName: string,
	dirname: string,
	options?: { entry?: string; plugins?: Plugin[] },
): UserConfig {
	const production = process.env.NODE_ENV === "production";
	const entry = options?.entry ?? "src/index.ts";

	return defineConfig({
		// Use relative URLs for assets (fonts, etc.) in CSS
		base: "./",
		plugins: options?.plugins ?? [],
		build: {
			outDir: resolve(dirname, `../../dist/webviews/${webviewName}`),
			emptyOutDir: true,
			// Target modern browsers (VS Code webview uses Chromium from Electron)
			target: "esnext",
			// Skip gzip size calculation for faster builds
			reportCompressedSize: false,
			// Webviews load as a single bundle; code-splitting doesn't apply
			chunkSizeWarningLimit: 600,
			rollupOptions: {
				// HTML is generated by the extension with CSP headers
				input: resolve(dirname, entry),
				output: {
					entryFileNames: "index.js",
					// Keep fonts with original names for proper CSS references
					assetFileNames: (assetInfo) => {
						if (assetInfo.names?.[0]?.endsWith(".ttf")) {
							return "codicon.ttf";
						}
						return "index.[ext]";
					},
				},
			},
			// Keeps extension size down; build locally to map stack traces
			sourcemap: !production,
		},
		resolve: {
			alias: {
				"@repo/webview-shared": resolve(dirname, "../webview-shared/src"),
			},
		},
	});
}

/**
 * Create a Vite config for a React-based webview package.
 */
export function createWebviewConfig(
	webviewName: string,
	dirname: string,
): UserConfig {
	return createBaseWebviewConfig(webviewName, dirname, {
		entry: "src/index.tsx",
		plugins: [react(), babel({ presets: [reactCompilerPreset()] })],
	});
}
