name: PR Auto Assign

on:
  pull_request_target:
    types: [opened]

permissions: {}

jobs:
  assign-author:
    permissions:
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Assign author
        uses: toshimaru/auto-author-assign@a78a94b219445cece8ccf0d45fec60af449f212a # v3.1.0
